* Проповіді
** Проповідь Епіфанія про марнотратство
[[https://www.facebook.com/share/p/59KVAyFEK9F6xzWJ/][Посилання]]
[[https://www.facebook.com/share/p/1AnLNv793K/][Проповідь день свята Обрізання Господнього]]
[[https://www.facebook.com/share/p/1BJdbin5GS/][Про покаяння]]

** Ігор Плохой
[[https://www.youtube.com/watch?v=Y9msxyu-1Ls][Боже, відкрий нам очі, на Твою реальність!]] звідси [[https://youtube.com/shorts/l83YPU62y8A?si=zEMEgg09iNQCvHXK][що таке віра]]
[[https://www.youtube.com/shorts/LX4jITshs-c][Про Слава Україні]]
[[https://youtube.com/shorts/rerFWhUF-70?si=EQGNsHbbS2b3X77w][Ісус про молитву]] Мт. 7.7
[[https://www.youtube.com/watch?v=0tkz8Wjq90g][Як віруючі стають невіруючими, а невіруючі віруючими?]] Фома невіруючий, Фомина неділя, Антипасха, Ів.XX 19-31
[[https://www.youtube.com/watch?v=F4sAA6AC7Qo][Як не втратити внутрішній мир під час війни?]] Мир Христовий, мир світу
[[https://www.youtube.com/watch?v=opPs6Eoz_Mw][Не будь невдоволеним]] Про господаря та наймитів, Блудного сина. Мт. XX, 1-16
[[https://youtu.be/hoAVGNtabSM?si=iHl4_R2T936SZ4lX][Яких ворогів любити? З якими воювати?]] Лк. 26 зач. 6:31-36
[[https://www.youtube.com/watch?v=Ur8Vj-bCOPI][Як любити своїх ворогів, коли вони тебе вбивають?]] Лк. 26 зач. 6:31-36
[[https://www.youtube.com/watch?v=6WF6bFGguuw][Притча про таланти]].
[[https://www.youtube.com/watch?v=s_vXXR2Qy74][Бери приклад з воїна, збудовуй свою віру]]! Віра дорівнює дія. Будь добрим воїном.
[[https://www.youtube.com/watch?v=UcoDbP1kbxM][Чому Бог бариться]]?  Про незрозумілу людям логіку Божих діянь. за цілі та терміни, строки відповідає Господь. А я робитиму свою справу, буду ходити у вірі.
**** [[https://www.facebook.com/100003450434954/posts/9696560110468907/?mibextid=rS40aB7S9Ucbxw6v][Річниця реформації]].
 31 жовтня - День Реформації! (Свято і для католиків і православних?)
 Вітаю усіх християн з цим святом! Не лише протестантів, а і католиків, і православних!
 Як би упереджено хто не ставився до цієї важливої історичної події, що суттєво вплинула на теологію "плюси" від процесу Реформації отримали як католики так і православні.
 Римо-католики започаткували рух Контрреформації, який протестанти сприймають. звісно, не надто позитивно, але для РКЦ цей рух народив орден Єзуїтів та єзуїтські школи, єзуїтську всесвітню місіонерську роботу. А Тридентський собор (1545–1563) систематизував католицьке вчення, в наслідок чого було відкинуто зловживання, уточнено догмати віри. Відбулося зосередження  на Святому Письмі та церковній дисципліні. З"явилися нові видання та коментарі до Біблії. Почалася глибша робота з вірянами, акцент на катехизації. Та ще багато процесів, які мали позитивний вплив на Римо-католицьку церкву.
 Щодо Православної церкви України та Східної Європи, то Реформація дала поштовх до: Видання Острозької Біблії (1581 р.). Започаткування друкарень Івана Федорова, Франциска Скорини. Поширення Святого Письма серед простого народу. Виникнення православних братств — активних мирянських об’єднань, що спонукало простих вірян до активної участі в житті та вирішені проблем Православної церкви. З’являється українське бароко, духовна поезія, літописи. Формується новий тип церковної культури з національним характером.
 В зв"язку з цим, у цей день, хочу нагадати усім: і протестантам, і православним, і католикам, що Церква завжди реформується, доки Христос не прийде й не відновить усе у Своїй славі! Тож, роботи ще у нас багато, починаючи від реформації власного внутрішнього світу кожного окремо взятого християнина, до реформації Церкви відповідно до вимог Святого письма дією Святого Духа, і аж до реформації усіх сфер нашого українського суспільства на основі принципів Слова Божого!
 2 важливих висновки:
 1. «Ми ж усі, відкритим обличчям, як у дзеркалі, дивлячись на славу Господню, змінюємось у той самий образ від слави в славу, як від Господнього Духа.» (2 Кор. 3:18). Справжнє реформування — це безперервне перетворення віруючих у Христоподібність.
 2. «І все, що тільки робите словом чи ділом, — усе робіть у Ім’я Господа Ісуса, дякуючи Богові й Отцеві через Нього.» (Кол. 3:17)
 Євангеліє має пронизувати всі сфери життя — працю, мову, поведінку.
** Проповіді Вадима Лисенка
*** Притча про весільний бенкет. Мт. 22:1-15, Лк. 14:16-24
[[https://www.facebook.com/reel/2039014139872829][Part 1]] [[https://www.facebook.com/reel/448522524935937][Part 2]] Багато званих, та мало обраних, Вбивство під час весілля
[[https://www.facebook.com/reel/1536840093981876/?mibextid=rS40aB7S9Ucbxw6v][Як вірити в Бога знаючи про все горе, що є в світі]]?
[[https://www.facebook.com/reel/1140449804279098][Що таке страх Божий]]
[[https://www.facebook.com/reel/1163587415285385][Чому Бог Старого Заповіту злий?]]
[[https://www.facebook.com/reel/1108956757587180][Крах імперій]]
[[https://www.facebook.com/reel/3570842829887324][Чому Христос забороняє називати людину дурною]]
[[https://www.facebook.com/reel/1363623044924085][Як диявол розбиває сім’ю?]]
[[https://www.facebook.com/share/p/16e48sgaqB/][Неправедний суддя і жінка]] або чому потрібно молитися. Лк. 18.1
[[https://www.youtube.com/watch?v=mRX-fPhVgNs][Завжди молитися і не занепадати духом]]!
[[https://www.facebook.com/reel/682498508070556][Молитва є духовною війною]].
[[https://www.facebook.com/reel/792610336687861][Хто такий Бог Ч1]].
[[https://www.facebook.com/reel/2759299327611671/?mibextid=rS40aB7S9Ucbxw6v][Чи вся влада від Бога?]]
** Проповіді Василь Колодій
[[https://fb.watch/wdaVcNeNqS/][Про самотність, духовні дари, присутність Бога]]
[[https://www.facebook.com/reel/8519974611416227][Про перебування у чистиліщі]]
[[https://www.facebook.com/reel/602131205568602][Про хустинку в Церкві]]
[[https://www.facebook.com/reel/395473806836060][Сповідь та причастя невічаних]]
[[https://www.facebook.com/reel/442689468302624][Про причини хвороб, бід]], духовний закон, зцілення
[[https://www.facebook.com/reel/1445831989728044][Усе у свій час]]. У Бога є план на кожного з нас. І кожен з нас має бути спасенний і має бути щасливий.

** Проповіді Денис Таргонський
[[https://www.facebook.com/share/p/j9LhLSZXvj1Vo5ZU/][Про Клайва Льюіса]]
[[https://www.facebook.com/share/p/aSQdDuhjqwXW4WQF/][Про св. Миколая]]
[[https://www.facebook.com/share/p/156YHyxGWx/][Трьох святителів, Григорія Богослова]] (2025-01-31)
[[https://www.facebook.com/100000832017435/posts/9284643371573304/][Сенс Хреста]]
[[https://www.facebook.com/share/p/158sZzPUio/][Григорій Палама]]

** Проповіді Роман Братковський
[[https://www.facebook.com/reel/554290624098834][Людина яка живе без Бога і помре, опиниться у пеклі]]. Кого Бог любить, того +карає+ дисциплінує
[[https://www.facebook.com/reel/573696285559700][Про наше покликання]], щастя, стрес, депресію
[[https://www.facebook.com/reel/789995797122403/?mibextid=rS40aB7S9Ucbxw6v][Хочеш бути щасливий, спасенний — Його слухай]]. Не дано нам іншого імені, через якого ми могли б спастися.
[[https://www.facebook.com/reel/1342039433642549][Хто такий Святий Дух]]
[[https://www.facebook.com/reel/590528813656088][Про наслідки порушення Заповідей]] Терниста, благословенна дорога
[[https://www.facebook.com/reel/3955503424777027][Про причини страждань]] та нашу відповідальність
[[https://www.facebook.com/reel/1306087084177597][Алкоголізм, наркоманія, Блуд і т.і.]]
[[https://www.facebook.com/reel/1099431491726403][Про слова прокляття]]
[[https://www.facebook.com/reel/1099431491726403][Про права, які надаємо сатані]] через відьом. І про благословення від священника. Про пороки.
[[https://www.facebook.com/reel/8728873347231315][Про свящеиків-відступників]], духовну сліпоту
[[https://www.facebook.com/reel/562980243117546][Про магію в Церкві]], духовну сліпоту, війну
[[https://www.facebook.com/reel/1295736164956650][Як сповідуватися]]
[[https://www.facebook.com/yevan.heliye/videos/775058585392053/?mibextid=rS40aB7S9Ucbxw6v][Про сповідання гріхів, особливо смертних]]. Чому зло потрібно винести наверх.
[[https://www.facebook.com/reel/2347716779015984][Речі, які несуть прокляття]].
[[https://www.facebook.com/reel/1777003689604313/?mibextid=rS40aB7S9Ucbxw6v][Йога, це диявольська практика]].
[[https://www.facebook.com/reel/1341890044230292][Розчарування бо нема відповіді від Бога]]. Бо ти зациклений на собі. Ми хочемо заслуговувати, а брати по вірі — не хочемо.
[[https://www.facebook.com/reel/1984634525328463][По вірі твоїй буде тобі]]. Ти запускаєш події своєю вірою. Амінь (нехай так буде).
[[https://www.facebook.com/reel/1840191423389121][Чому ходити до Церкви]], про мудрість
[[https://www.facebook.com/reel/7919745894808479][Десятина]], жертва Богу, сіяння та жатва
[[https://www.facebook.com/reel/1102933151485623][Про невір'я]] і дію Святого Духа, народження віри
[[https://www.facebook.com/reel/2330176040682013][Сниться покійник]] некромантія
[[https://www.facebook.com/reel/935002918684735][Сенс віри]] і її плоди та зміни в тобі
[[https://www.facebook.com/reel/598106163066757][Воля Божа]]
[[https://www.facebook.com/reel/1151905469947319][Віра -> Оправдання -> Надія -> Мир -> Любов -> Щастя]]
[[https://www.facebook.com/reel/457659067329302][Не вибачайся, коли невинний, але покайся, коли винний.]]
[[https://youtu.be/nq6WCIb_ULs?si=IsBwJHkUXhilHSxE][Стрітення або Чому я не щасливий?]] Закхей.
[[https://www.facebook.com/reel/481904348136612][Радості нема]], сенсу життя нема. Призначення.
[[https://www.youtube.com/watch?v=ro5syxP4hPE][Про митря та фарисея]] як праведність працює проти Бога. Справедливість.
[[https://youtu.be/rON8krvin_A?si=zTgpHU8kUIEFuRzp][Неділя блудного сина]] !!! Республіканці чи Демократи? Про цінності. Буква вбиває, а Дух животворить. Як поєднати Закон та Вільність 42:30
[[https://youtu.be/mwGr02EQ6JA?si=UEwdjTQnkQcIewlg][Покликання Андрія, Симона-Петра, Пилипа та Нафанаїла.]] Про справедливий мир.
[[https://www.youtube.com/watch?v=tlAg2DFM2Q8][Самозречення і несіння хрестів]]  Мт 16
[[https://www.youtube.com/watch?v=cRYJMph0ero][Візьми свій хрест і іди за Мною]].
[[https://www.youtube.com/watch?v=JHrEImjg8LY][Зцілення паралізованого у Капернаумі]] Неділя розслабленого Мт (9: 1–8), Мк (2: 1–12) Лк (5: 17–26)
[[https://www.youtube.com/watch?v=Ms_-uRIBpVE][Преображення Господнє, вигнання біса з хлопчика]], втрата віри. молитва та піст 21хв, як ходити в силі Христа 23хв. Мк.(9, 17-31)
[[https://youtu.be/HSWCyfnX7Qk?si=PEnLQ4kLsBEyEo1c][Вигнання біса з хлопчика, як не змогли учні]] Мк. 40 зач. IX, 17-31
[[https://www.facebook.com/reel/1641304970594223][Ісус є їжа духа та тіла]]
[[https://youtube.com/shorts/gJrkr-T_AwI?si=LQ2cjPISqz3YRxGS][Гнів та емоції.]]
[[https://www.facebook.com/reel/547684961581772][Про Воскресіння]] і наслідки
[[https://www.facebook.com/reel/912243930762460][Бог може але не робить]]
[[https://www.facebook.com/reel/2846173708886140][Три джерела зла]]
[[https://www.facebook.com/reel/1156408169566045][Хто такий Дух Святий]]? /Той, хто живе в тобі/
[[https://www.youtube.com/shorts/4ALSOHrn-n0][Як молитись.]] Довіра.
[[https://www.facebook.com/reel/654938770353005][Про невиправдання темпераментом, емоціями]]
[[https://www.facebook.com/reel/1277076086954048][Про непрощення]]. /Коли ти не простиш, то і тобі непроститься/
[[https://www.facebook.com/reel/665684966402391][Сатана vs Бог]]
[[https://www.facebook.com/reel/1197405381927182][Жоден гріх не був би прощений, якби Ісус не помер і не воскрес]]. Сповідь.
[[https://www.youtube.com/watch?v=gb26Frfu-YY][Ісус каже, ніколи нічого не бійся]]
[[https://www.youtube.com/watch?v=Ub5oDj377Aw][Еволюція учня Ісуса]] Фома невіруючий, Фомина неділя, Антипасха, Ів.XX 19-31
[[https://www.facebook.com/reel/604074962382605][Жити як ти хочеш...]] Я сам, без Бога, початок падіння
[[https://www.facebook.com/reel/1026044309475243][Не Бог жорстокий, а ми самі запускають зло у своє життя]]. Наслідки наших дій.
[[https://www.youtube.com/watch?v=iNL6SFdA5TE][Жон-мироносиць]] Мк. XV, 43 - XVI, 8, ієрархія цінностей
[[https://www.facebook.com/reel/1365100128332737][Не ікона зціляє, а благодать Божа...]] Бог намагається достукатись через щось, бо ми нічого не робимо.
[[https://www.facebook.com/reel/913492217570975][Жодна молитва не робить те, що робить Літургія]]!
[[https://www.facebook.com/reel/920969226590801][Гендерну ідеологію ввели в школах, а Ісуса викинули, залишили тільки і тюрмі]].
[[Біблія закодована][https://www.youtube.com/shorts/bZ5e9GGp8bY]]
[[https://www.facebook.com/reel/1220224509759323][Сатана ніколи не стане сильніше Бога, бо є творінням]]. Але він сильніше за людину. Тому перемогти можемо тільки з Ісусом, який помер і воскрес за нас.
[[https://youtu.be/HSWCyfnX7Qk?si=0kBtJ1AD3OpXr9iF][Зцілення біснуватого хлопчика з епілепсією.]] якого не могли зцілити учні Ісуса.
[[https://youtu.be/Ig8VvLP663M?si=ZYbb-EJMB3ChptmS][Не турбуйтесь як жити]] Мф, 18 зач. VI 22-33
[[https://www.youtube.com/watch?v=EF1cJIIVgcw][Зцілення слуги сотника 1.]] З Божою благодаттю життя у любові і без страху.
[[https://www.youtube.com/watch?v=7dd7JWLUXdY][Зцілення слуги сотника 2]]. Позиція влади: зцілення слуги сотника
[[https://youtu.be/2ByzNfRxuqU?si=0rlBwN1vExzGpMNF][Зцілення біснуватого в краї гадаринському.]] Ісус шукає найгірших!
[[https://www.facebook.com/reel/743813734770483][Християнство не забирає право вибору, а дає його.]] Якщо нема Христа, Євангелія, то і вибору нема, є тільки гріх. "Кожен, хто повірить і охреститься, буде спасенний, а хто не повірить, буде засуджений" (Мк 16:16)
[[https://www.facebook.com/reel/826863027169094/?mibextid=rS40aB7S9Ucbxw6v][Жива і мертва віра.]] Віра без діл мертва! діла без віри також мертві!
[[https://www.youtube.com/watch?v=tomKMTh5bGs][Я нічим не буду хвалитися, крім Христа]]
[[https://www.youtube.com/watch?v=uooiTka8maA][Я буду вам Отцем, а ви будете мені синами й дочками]]. 17 неділя після П'ятидесятниці. Про зцілення дочки хананеянки.
[[https://www.youtube.com/watch?v=1pdOOTDvIzU][Хочеш мати - давай]]! 18 неділя після П'ятидесятниці. Про покликання ап. Павла.
[[https://www.youtube.com/watch?v=7j_P3vp3bJg][Чи є вбивство на війні гріхом?]] Любіть ворогів ваших. Лк. 26 зач. 6:31-36
[[https://www.youtube.com/watch?v=__eLFkqICXw][Притча про таланти - не закопуй а примножуй]].
[[https://www.facebook.com/reel/1553659655651795][Брати наші протестати]].
[[https://www.facebook.com/reel/2322362131566967][Як запропонувати піти до Церкви]].
[[https://www.facebook.com/share/v/17KwJR4T7V/?mibextid=rS40aB7S9Ucbxw6v][Для чого Ісус помер]]? Для чого нам Ісус. Звідки він нас вийняв.
[[https://youtube.com/shorts/2F5nR9uDkG0?si=P-4Kp7I7EkXmRwLX][Чому блудникам простіше увійти в Царство Небесне]]? Блудний син.
[[https://www.facebook.com/share/v/1G7FBnC9L2/][На основі чого ти лпреділяєш добро чи зло]]? Вільність приведе тебе до рабства.
[[https://www.youtube.com/watch?v=3pRR45JG-7g][Плідна земля]]. Про сіяча. Лк. 8:4-15;Мт. 13:1-17; Мк. 4:1-12
Багач і Лазар. [[https://www.youtube.com/watch?v=OEdNrYztF-U][Раз]], [[https://youtu.be/4ds_5XNJej0?si=NANDAUkr_0PrFUr1][два]]. Лк 16:19-22
Про легіон бісів. [[https://youtu.be/2ByzNfRxuqU?si=HMd5s3yTXGYZ2S9g][Раз]], [[https://youtu.be/M8Cg3bJmEzM?si=HiCI3RGoO1JGBy06][два]]. Еф. 2:4-10, Лк.8:26-39
[[https://youtu.be/KLTRh6uxMlc?si=0vtguOJBHtWDRHYQ][Зцілення кровоточивої та доньки Іаіра]]. Лк.8:41-56

** Роман Грищук
[[https://www.facebook.com/share/p/1HV3Z8TGvz/][Чи вся влада - від Бога?]]

** Проповіді Іван Пендлишак
*** Чому Бог принижує людину?
[[https://www.youtube.com/watch?v=KhKEjVApg74][Посилання]]
19:40 - 22:50 проти гординині Лк.18:9-13 /про митаря та фарисея/
22:50 - 27:00 причини та види приниження; Єремії 3:25-36
27:00 — 35:20 про тих, хто своїм життям позорить Бога, нерозрізняє праведне та грішне; Єзекиїля 22:23-29
35:20 Бог не скорий на розправу, але поверне приниження.
39:30 Не вічно гнівається Господь
[[https://www.facebook.com/reel/1260502695154899][Інтернет-залежність]] растлєніє, забруднення
[[https://www.facebook.com/reel/589245847118665][Про радість]]
[[https://www.facebook.com/reel/2628144977376799][Про спроби обманути Бога]] (прийти до Бога в старості)
[[https://www.facebook.com/reel/292406969862902][Не капайте на мізки]]
[[https://www.facebook.com/reel/916222924046802][Маючи поживу і одяг, будемо вдячні Господеві]] про заздрість та радість
[[https://www.facebook.com/reel/1398296791137600][Одні умніки кругом]] або будьте як діти
[[https://www.facebook.com/reel/3348413735289641][Причини страху]]. Свобода. Ісус рятує під час шторму.
[[https://www.facebook.com/reel/1608087846809737][Про довіру Богу]] і живу віру
[[https://www.facebook.com/reel/1622762191645267][У скандалістів ніколи не буває радості]]
[[https://www.facebook.com/reel/1510701416279032][Ти вже в пеклі. Бог каже виходь звідти...]]
[[https://www.facebook.com/reel/534311562996217][Труднощі як Божий план для зміцнення нашої віри]] Чи вистоїть віруючий до кінця?
[[https://www.facebook.com/reel/607160192308140][Як уберегтися від пекла]] (образи, ревнощі, Фиип'ян 4.8)
[[https://www.youtube.com/shorts/8pHR5Spv-Ew?si=4mMUXj0lB8AvrWsu][Бог любить вдячних]]
[[https://www.facebook.com/reel/558976606919675][Про випробування]], трудності, покарання, покаяння, нагороду, перестати роптати. Промисел Божий.
[[https://www.facebook.com/reel/442279015542763][Самозречення]]

** Проповіді Романа Лаби
[[https://www.facebook.com/reel/1098627201978545][Про лицемірство]] та ієрархію цінностей (гріхів)

** Проповіді Сергія Накула
[[https://www.facebook.com/permalink.php?story_fbid=pfbid02KZX9qBynXgWfRstp8jtMd58Gdw8FTdmSxp8hgrRrUqdkZVxc2HTSikxgnQwdRxFPl&id=100071344247029][Скандал Різдва]]
[[https://www.facebook.com/100071344247029/posts/pfbid0CZUcHxDUvaRUS6VqTh2cQgJGV7cnnpaGF9ATtRAArWpoNVWTeupSSdm9MUP8ZkS5l/][Про Різдво 2]]
[[https://www.facebook.com/share/p/1BjPKWyXkN/][Сім основних причин, чому Різдво має значення]]
[[https://www.facebook.com/100071344247029/videos/420793981104397/][Про надію]], адвент
[[https://www.facebook.com/100071344247029/posts/pfbid02m5YCD9z8qCWVndRVAvUpsh3p7huy6brP8TrEWX8NfxgxRnRgc9GqhHUNAAnzTLZEl/][Різдво це також подія зі сльозами на очах[1].]] [[https://www.facebook.com/share/p/18Rtw97pNz/][[2]​]]
[[http://www.god.in.ua/?p=20288][Царство Боже усередині нас]] /збережено/

** Проповіді Михайла Паночка
[[https://www.facebook.com/reel/1787860745291638][Коли залишає Ісус]], Храм — не головне, для Ісуса гоовне людська душа
[[https://www.youtube.com/shorts/bZ5e9GGp8bY][Як не засуджувати]]
[[https://www.youtube.com/watch?v=dg1W4hsxJus][Які плоди принести Богу?]]

** Любомир Гузар
[[https://www.facebook.com/reel/539303945640749][Чому помирає молодь]]

** Андрій Дудченко
[[https://www.facebook.com/share/p/zy7BQTC2XzmUGZVK/][Релігія як інструмент і зброя у гібридній війні Росії проти України]]
[[https://www.facebook.com/share/p/1KgLkDtaU5/][Роль мирян у Церкві]]
[[https://www.youtube.com/watch?v=4SbAtAqS0KA][Неділя про блудного сина]]
[[https://www.facebook.com/share/p/16HK3RnABM/][Євхаристійну молитву не тільки перестали читати вголос...]]
[[https://www.youtube.com/watch?v=FJQrHul6NWk][Про сповідання апостола Фоми, пришестя Христове і наше очікування. Слово у неділю Фомину, Антипасху]] ([[https://www.facebook.com/watch/?v=1024851639255637][FB]])
[[https://www.facebook.com/share/p/1NCSHkzJVy/][Р. Бокем, Ісус та жінки, 87-88.]]
*** [[https://www.facebook.com/share/p/1CJ75BXTN9/][Слухання і любов]].
СЛУХАННЯ І ЛЮБОВ
На початку 6-ї глави Второзаконня ми читаємо Шема, яка є водночас і сповіданням віри Ізраїлю в YHWH як єдиного Бога, і ствердженням «найбільшої заповіді Закону», заповіді любові: «Слухай, Ізраїлю! Господь, Бог наш, Господь єдиний. І люби Господа, Бога твого, всім серцем твоїм, і всією душею твоєю, і всією силою твоєю» (Втор 6:4-5).
Як відомо, це проголошення – один із центрів, навколо яких після зруйнування Храму будується синагогальна молитва. Повторюючи щодня Шема, кожен ізраїльтянин закриває очі рукою, символізуючи, що таїнство віри, проголошене цими великими словами, є таїнством, доступним лише слуханню, але не баченню.
СЛУХАННЯ, ЗУМОВЛЕНЕ ЛЮБОВ’Ю
Однак найважливіший внесок Шема в нашу тему – це єдність, яку Шема встановлює між слуханням і любов’ю до Бога. Як уже було сказано, фундаментальною умовою справжнього слухання Слова є вірна любов до Того, Хто через це слово звертається до нашого серця. Тепер можемо додати: без абсолютної віри в єдиність нашого Бога, без радикальної любові до Нього наше серце залишається закритим для слухання Його голосу. Гадаю, тут ми досягаємо таємничого центру, сокровенного ключа всього біблійного богослов’я слухання: справжнє слухання має бути саме «всім серцем, усією душею, усіма силами».
Радикальність і цілісність любові до Бога, запропоновані в Шема, – такі самі, як ті, що потрібні для слухання Його слова: любити Бога і слухати Його голос – це наче два аспекти однієї й тієї самої реальності, дві різні формули однієї й тієї самої фундаментальної заповіді.
СЛУХАННЯ І ЛЮБОВ АЖ ДО МУЧЕНИЦТВА
Одна з головних проблем юдейської екзегези Шема, яка переконана, що в Писанні ніколи не може бути нічого випадкового чи зайвого, полягає у визначенні цих трьох речей, якими слід любити Бога. Якщо вже сказано «всім серцем», то який сенс має додавання «всією душею і всіма силами»? Відповідь, кодифікована вчителями Мішни (II століття від Р.Х.), полягає в тому, що уточнення «всією душею» означає «аж до того, коли Він забере душу», тобто до мучеництва; а додавання «всіма силами» означає «всім твоїм майном (мамон)».
З текстуальної точки зору така екзегеза може здаватися нам натягнутою, однак це не банальна спіритуалістична екзегеза, що спорожнює зміст вимог любові до Бога. Навпаки, вона конкретизує ці вимоги з великою інтенсивністю в кожному, внутрішньому і зовнішньому, вимірі існування: Бога слід любити не лише всім своїм єством (серце), але також усіма своїми матеріальними благами (сили), аж до повної віддачі життя (душа).
ТРИ КАТЕГОРІЇ СЛУХАЧІВ СЛОВА ЗГІДНО З ЄВАНГЕЛІЄМ
Якщо розглянути, хоча б у загальних рисах, те, що в Євангеліях найвиразніше відображає тему слухання, тобто притчу про сіяча та її пояснення (Мф 13; Мк 4; Лк 😎, гадаю, ми побачимо досить чіткий тематичний збіг із юдейською екзегезою Шема.
Дійсно, згідно з євангельською притчею, ті, хто не здатні прийняти Слово Боже, як відомо, поділяються на три різні категорії: 1) ті, чиє серце не здатне зрозуміти Слово (Мф 13:19); 2) ті, хто не залишаються вірними в скорботах і гоніннях за Слово (Мф 13:20-21); 3) ті, які зваблені багатством (Мф 13:22).
По суті, ті, хто, згідно з Євангелієм, не здатні слухати Слово Боже, – це ті самі, хто, згідно з юдейською екзегезою Шема, не здатні любити Бога: а) всім серцем; б) всією душею, тобто в стражданнях і муках; в) всіма силами, тобто втрачаючи всі свої багатства.
Аналогічно слід тлумачити і три категорії доброї землі, тобто тих, хто здатні слухати, хто вирощують насіння Слова, і воно приносить плід (Мф 13:23).
ЗАКЛЮЧЕННЯ
Якою б не була переконливість цієї екзегези, мені здається незаперечним, що притча про сіяча продовжує тематику Шема і йде слідами її духовного тлумачення. Головне наставлення Шема досягає своєї повноти в Євангелії: лише той, хто любить Господа, свого єдиного Бога, дійсно здатний до слухання, до духовного розуміння слова Божого в тій цілісності, яка робить нашу любов більш відповідною тій любові, яку Він явив нам.
Мелло. Слухай, Ізраїль!

** Олександр Дедюхін
[[https://www.facebook.com/100001350299129/posts/pfbid031jrDbbdanyd1wxVLZg9xrhDPQ68wGTVUesf624jmwiP2j3fqBokdGd1hoSgHDjbil/][Різдво - це прийняття Спасителя та радість, дарована Ним]].
[[https://www.facebook.com/share/p/152vgi44aY/][У Господа немає невдах]]
[[https://www.facebook.com/share/p/18XchQaDBV/][Для чого випробування]]
[[https://www.facebook.com/100001350299129/posts/9246063345448583/][Святий Дух приходить, щоб оновити, очистити й запалити.]]
[[https://www.facebook.com/share/p/14nj4dcGQm/][Наша молитва — це наш зв’язок із тими, хто пішов.]]
[[https://www.facebook.com/100001350299129/posts/9277744175613833/][Неділя про блудного сина]]
[[https://www.facebook.com/share/p/181jCVjqJL/][Cтати кращою версією самої себе". Наш єдиний вихід: стати такими, якими бачить нас Бог]]
[[https://www.facebook.com/100001350299129/posts/9409641709090745/][Неділя торжества Православ'я]]
[[https://www.facebook.com/share/p/1BjLnBvtBm/][Про піст]]
[[https://www.facebook.com/share/p/1BASdZ8NPN/][Я — подих Божий]], тому мені даровані можливості
[[https://www.facebook.com/share/p/12GZBdMLnhb/][Хрестопоклонна неділя]]
[[https://www.facebook.com/share/p/1BWkVtZCvn/][Церква – це лікарня]]
[[https://www.facebook.com/reel/1277076086954048][Христос — помазанник]] на Царство. Мт. 26:13 Лк.7 36-50
[[https://www.facebook.com/share/p/1DK7A687HY/][Поховання Ісуса та Жон-мироносиць]]. Мк. XV, 43 - XVI, 8
[[https://www.facebook.com/share/p/1AWpQCL3pE/][Бути пророком — це жити. А жити — означає зневажати імперію.]] Пророк Даниїл і ми.
[[https://www.facebook.com/share/p/16nPcsYC91/][Різдво Іоана Предтечі]]
[[https://www.facebook.com/100001350299129/posts/23989693147325693/][Петра і Павла]]
[[https://www.facebook.com/100001350299129/posts/23989693147325693/][Трійця]]
** Феогност Пушков
[[https://www.facebook.com/abbasthg/posts/pfbid02GWHY2YsgowzxXyRWba8WvLed7q4ryPj5hLsLpJvp2L6ndjHqL1mK5XwNXtLEzTVVl?rdid=u80zlfjJMVKnLENg][Посилання на книги Бенедикта 16-го]]
[[https://www.facebook.com/abbasthg/posts/pfbid0uBvEjPAEabTRiZCQ7pX4sXcCWj3cMUntwRmL5FV72QL29RdQKc5z7zB7mbrernRWl?rdid=PcdpHKMchYxVceSs][Богопізнання]]

** Сергій Степанюк
[[https://www.facebook.com/reel/1260400348702551][Про Трійцю]]
[[https://www.facebook.com/reel/676726480884880][Чому помер Христос]]
[[https://www.facebook.com/reel/1464163971155561][Чи треба молитися за померлих?]]
[[https://www.facebook.com/sergii.stepaniuk/videos/1044857689922926/?mibextid=rS40aB7S9Ucbxw6v][Чи можна жінкам носити штани?]]
[[https://www.youtube.com/watch?v=EHZAXF2Vh68][У Марії були ще діти після народження Ісуса?!]]
[[https://www.facebook.com/sergii.stepaniuk/videos/844789674253984/?mibextid=rS40aB7S9Ucbxw6v][Чому Бог не знищив диявола?]]
[[https://www.facebook.com/reel/628023469786374][Раб Божий]]
- «Я – Господь, твій Бог, Який тримає тебе за праву руку, і каже тобі: Не бійся, Я тобі допомагаю» (Ісаї 41:13)
[[https://www.facebook.com/sergii.stepaniuk/videos/8605127036181502/?mibextid=rS40aB7S9Ucbxw6v][Навіщо ставлять свічки в Церкві]]?

** Генадій Коваленко
*** [[https://www.facebook.com/share/p/17GgEqRLav/][Трьох святителів]]
Спробую, отче, стисло, як вийде, описати шлях, який я пройшов..а там Вам вирішувати.
Декілька років тому, така сама біль пробила мене. Навіть зупинив авто, їхав у відрядження, вийшов і горлав на все поле. Кожен по різному реагує на сімейні драми..
І вот приповз, потім, до протоієрея Геннадія Маркова, ви ж знаєте його. Мій духовний Батько.. і отримав завдання, читати 40 днів акафіст. О 19.00.
Понеділок - Ангела Охоронця, з ним треба налагодити зв'язок.
Вівторок - Іван Предтеча, Середа - Всецариця, Четвер - Микола Чудотворець, П'ятниця- муч. Гурій, Самон, Авів, Субота - вел. муч. Пантелеймон, Неділя - Покрова.
І додатково поради від психологів - тільки підкатує біль, перемикати думки на роботу, щось інше. Можна резинку на кість руки і себе лупити, як тільки понесло. І фізичні вправи до нестями, хоч робота, хоч спорт.
Через 40 днів ви себе не впізнаєте. А через ще час, у Вас буде подарунок від Бога.
Це екзамен. Ви або здаєте і нагорода, або шлях донизу.
Ви людина Світла. Обрали Шлях. Тому всі відповіді знаєте...
Нехай Господь охороняє Вас. [[https://www.facebook.com/share/p/18q42uodvh/][Відси]].
*** Зростання
Усі ми зростаємо протягом усього життя.
В дитинстві - вгору. В школі (виші) - до дня випуску. В  коханні наш шлях встелений  розбитими серцями (хтось не любив нас, кимось не зацікавилися ми).
Вже потім людина ЧОМУСЬ вирішує припинити своє зростання ''вгору'' та якісно. Але сам процес росту не припиняється. І ми продовжуємо рости, але вже ВШИР. Та, через деякий час, через суглоби та життєдіяльність, ми збільшуємо тиск на Планету. В прямому та переносному смислах.
Людство, за неповне покоління, підперло хмари звалищами СВОГО сміття. Ми - Цивілізація, яка залишить пособі свої піраміди. Піраміди Сміття.
Те саме усі ми залишаємо і в НЕматеріальному Вимірі.
''Плiд же духа є: любов, радiсть, мир, довготерпiння, доброта, милосердя, вiра,
лагiд­нiсть, стриманiсть." (Послання до Галатів, 5:22-23).
Усе інше - складові  Сміття нематеріального. І його ми накопичуємо вже в самих собі. В Душах своїх.
Але Людство це не щось таке, до чого ми не причетні. Це, в першу чергу - сукупність окремого ''Я'' кожного з нас. Бо кожна Людина є цілим Внутрішнім Світом з Власним Мікрокосмосом навколо себе.
Наше ставлення до Внутрішнього Власного визначається тількиті та виключно нашим власним Вибором. Нашим особистим рішенням щодо вибору вектору зростання.
Це стосується і нашої Душі та нашої Духовності, яку ми продукуємо на Ближніх.
Ключем від Врат Вибору, які відкривають нам новий Простір Світла, є Знання. Але купити можна хіба що тільки диплом. Знання в собі можна тільки зростити. Вектор Росту Вшир в нас вже є. Для росту якісно вгору його треба тільки перенаправити. І це можна зробити виключно через Власний Вибір. Вибір Сівача.
Апостол Павло наголошував вірним те саме:
- ''Хто сiє для плотi своєї, вiд плотi пожне тлiння, а хто сiє для духа, вiд духа пожне життя вiчне.'' (Послання до Галатів, 6:9);
- ''хто сiє скупо, той скупо i пожне, а хто сiє щедро, той щедро i пожне." (2 Послання до Коринф'ян, 9:6).
Я вже чув та читав відповіді про те, що зараз не час, бо війна. Що наразі час горя та сліз... 
Відповісти можу тільки словами царя Давида:
''Ті, що сіють зі сльозами, пожнуть з радістю.
Хто з плачем ніс сіяти зерно своє, той повернеться веселий, несучи снопи свої.''
(Псалом 125, стихи 5-6).
#Вибір_Сіяча це  Наше Рішення - ЩО сіяти, ДЕ сіяти та КОЛИ розпочати працювати.
Небажання зробити Вибір це також Вибір. Але Відсутність Плодів буде результатом цьому.

** Кирило Говорун
[[https://df.news/2025/01/25/arkhimandryt-kyryl-hovorun-hlobalne-pravoslav-ia-vidchajdushna-potreba-u-samootsintsi/][Глобальне Православ’я: відчайдушна потреба у самооцінці]]

** Володимир Василик
[[https://www.facebook.com/100017499633218/posts/1665971577329481/][Що таке Літургія та для чого вона звершується]]
[[https://www.facebook.com/100017499633218/posts/1665974733995832/][За що мені такі нещастя?]]
[[https://www.facebook.com/share/p/19nEeU6c7k/][Про поклони]]
[[https://www.facebook.com/share/p/1FDYUPQt2U/][НА ПЕРШЕ МІСЦЕ треба завжди ставити спасіння душі, і тоді всі наші земні турботи вирішить Сам Господь.]]

** Миколай Храпач
[[https://www.facebook.com/share/p/1AJyZMu4t4/?mibextid=rS40aB7S9Ucbxw6v][Любіть ворогів ваших]]. Лк. 26 зач. 6:31-36
[[https://www.facebook.com/share/p/1BtG9zrPeT/?mibextid=rS40aB7S9Ucbxw6v][Про сіяча]]. Лк. 8:4-15;Мт. 13:1-17; Мк. 4:1-12

** Володимир Омельчук
[[https://www.youtube.com/watch?v=vcM5GJjYh-8][Про радість]] (9:52) Відсутність радості — це відсутність Царства Божого, відсутність духовності (Дух Святий — це олива радості)
[[https://www.facebook.com/reel/1100064048481120][Прийде гордість, то прийде й посоромлення, а з смиренними мудрість.]] Скромність, гординя
[[https://www.facebook.com/reel/995474582481464][Для чистих усе чисте, а для занечищених і невірних нема нічого чистого, але їхній розум і сумління занечищені]]. «Добра людина з доброго скарбу серця свого виносить добре, а зла людина з злого скарбу серця свого виносить зле.»
(Біблія, Луки 6:45)
[[https://www.facebook.com/reel/1308607910189501][Все моє… чи все Його?]] Про "власні досягнення", вдячність за те, що маємо. «За те, що люди були неуважні до діл рук Господніх, і не зважали на чин Його, Він зруйнує їх і не збудує їх»
[[https://www.facebook.com/share/v/1BP3HiqyPL/][Про біль]] Утішитель, надія, переболіти
[[https://www.facebook.com/reel/1041348727808988][Гріх лицемірства]] маски, тест на фарисейство
[[https://www.facebook.com/100001287756061/posts/24573638982262353/?mibextid=rS40aB7S9Ucbxw6v][Сенс життя]]
[[https://www.facebook.com/share/v/1HTGvx5D9e/][Смирення]]
[[https://www.facebook.com/share/v/17Pd4RBJ5N/][Священицька місія шлюбу]]
[[https://www.facebook.com/reel/1151478410273299][Головний дефіцит сім'ї.]]
[[https://www.facebook.com/reel/1347892587119977/][5 ознак, що Бог сказав "ТАК" для створення сім'ї]].
[[https://www.facebook.com/reel/1341705580757475][Перехідний період]]. Нарікання, страх, довіра.
[[https://www.facebook.com/reel/1402360714828720/][Скунс проти ведмедя або коли мудрість сильніша за правоту]].
[[https://www.facebook.com/reel/2001780163999661][Я християнин чи напівфабрикат]]? Хеловін, суміщення християнства і нехристиянства з наслідками.
[[https://www.facebook.com/reel/1354041516264701][Інтелектуальна блювотина]]. Чию програму ти виконуєш, на якій основі ти будуєш своє життя?
**** [[https://www.facebook.com/share/p/1GpqXgds7Q/][Рай, щоб під ним не малось на увазі, без Бога — ілюзія]]…
Рай без Бога — концентрована ілюзія…
Уявіть: колись люди взимку прокидалися серед ночі, щоб підкинути дрова. Інакше діти промерзли б до кісток. Сьогодні ти просто крутиш термостат — і в домі тепло. 
Сьогодні більшість з нас приймають щоденно теплий душ, і взагалі не знаємо що ще 60 років назад такої розкоші в близько не було…
Це те, що стало нормою, хоча колись було недосяжною розкішшю.
Наш комфорт зріс. А відчуття задоволення — ні. І це найбільше видно в сім’ї.
Колись вам здавалося, що поруч — людина-подарунок. Але з часом з’являється відчуття, що щось бракує.
Очікування ростуть, а вдячність — ні.
І ми швидко починаємо думати, що проблема у партнері.
Але правда в тому, що проблема — в серці. Бо серце без Бога перетворюється на фабрику бажань.
Воно завжди хоче більше.
І ніколи не скаже: «Мені достатньо».
Справжнє щастя — це не ідеальні умови. Справжнє щастя — це базовий рівень життя мінус заздрість. 
А наситити те, що не насичується, неможливо.
Навіть у раю Адам і Єва відчули нестачу — проблема була не в умовах, а в серці.
У кожній людині є порожнеча, яку може заповнити тільки Бог.
І коли Бог не заповнює цю порожнечу — ми вимагаємо, щоб її заповнив партнер. Але жодна людина не відповідає цій функції.
Тому сім’я тріскає не там, де бракує умов, а там, де бракує поклоніння Богові.
Бо тільки Бог дає любов, яка не закінчується, і милість, яка не залежить від настрою.
І головне:
Сім’я стає раєм не тоді, коли все ідеально. Сім’я стає раєм тоді, коли Бог у центрі. Бо раю без Бога не буває, не живіть ілюзією…

*** Про щлюб та відносини
[[https://www.facebook.com/reel/1482031863146970/?mibextid=rS40aB7S9Ucbxw6v][Шлюб не тримається на весільних фото]]
[[https://www.facebook.com/reel/24617402957895862/?mibextid=rS40aB7S9Ucbxw6v][Знецінення — вбивця любові]]


** Інше
[[https://www.facebook.com/reel/1300493324781494][Світ вчить — люби себе понад усе. А великі мислителі усіх часів казали — лише любов до іншого відкриває шлях до справжнього життя]].
[[https://www.facebook.com/share/p/15tawGeSw6/][Є чотири речі...]]
[[https://www.youtube.com/watch?v=l8ouVEZ8mGk][Про несправедливого суддю та вдову]].
[[https://www.facebook.com/reel/812951331046297][Вплив диявола на ум]] (протестантка)
[[https://www.facebook.com/reel/1115702216926638][Кращі християнські фільми]]
[[https://www.facebook.com/share/p/1EL5JudT2e/][Плоди викрадення, або як Яків втратив благословення]]
[[https://www.facebook.com/reel/1602835433776922\\][Життєві бурі.]] Христос не гасив шторм, а звав Петра йти.  Незважаючи на все, що навколо тебе, ти можеш вийти і піти по воді
[[https://www.facebook.com/share/p/16A79VLfoE/][Ісус і перелюбниця]].
- Бог християн є Богом переміни . Приймаючи у своє серце терпіння, ти виносиш з нього мир, відкидаєш зневіру й бачиш, як народжується надія . Падре Піо.
- "Біжи від всіх, але люби всіх, не входи в чужі справи і не суди нікого - тоді і буде мир в серці . А поведешся з багатьма - все винесуть від тебе, що встигнеш зібрати в собі . Знайомства і розмови спустошують і розсіюють . Хтось повинен бути, з ким поділитися, без цього дуже важко і складно . Іноді це необхідно навіть . Але вибирати треба дуже обережно, треба бути впевненим в людині - не зрозуміють того, що для тебе цінно... Більше мовчи, вчися мовчання...". Ієросхимонах Михайло ( Піткевич )
 - Адже Царство Боже – не їжа й не пиття, а праведність, мир і радість у Святому Дусі.
Хто цим служить Христові, той і Богові до вподоби, і людьми шанований.
Тому дбаймо про мир і про те, що служить для збудування одне одного.
[[https://www.facebook.com/reel/1304051397611102/?mibextid=rS40aB7S9Ucbxw6v][‭‭Римлян 14‬:‭17‬-‭19‬]].
[[https://www.facebook.com/reel/833565982502634][Москалі — одержимі дияволом]].
*** [[https://www.facebook.com/100008284174916/posts/3821084191511016/?mibextid=rS40aB7S9Ucbxw6v][Притча про мудрих і нерозумних дів. ( Мф. 25,1 - 13 )]].
Святі Отці Церкви по - різному коментують цю Притчу . Але узагальнення їхніх думок допомагає зрозуміти те, про що Говорить Господь .
Образом “ діви ” Господь проявляє нам душу людини, яка прагне бути з Женихом - Господом . Мудра душа не лише знає про Господа і чекає на Нього, але ще й на протязі земного життя готує оливу для “ світильника ” - творить Божі справи на землі, які допомагають їй стяжати Святого Духа . А нерозумна душа - знає про Господа і бажає зустрічі з Ним, але добрих, Божих справ не вчиняє, навіть коли вважає що весь час тільки й робить добрі справи . Бо такі справи, на свій розсуд ( а особливо коли вона, заради добрих справ, ігнорує Богослужіння, сповідь та причастя, тому що інакше не вистачить часу на її добрі справи ) свідчать про небажання душі слухати Бога . Така душа не може стяжати Святого Духа . Тому, коли вона засинає ( помирає ), а проснувшись в новому житті, скільки б не взивала : “ Господи ! Господи ! Відчини ”, - у відповідь почує лише одне : “ Я не знаю тебе ”. А “ ті, які були готові, ввійшли з ним на весілля ”, бо вони сяяли світлом Духа Святого .
“ Отже, пильнуйте, бо не знаєте ні дня, ні години, коли Син Людський прийде ".
*** [[https://www.facebook.com/share/p/1BMNwaYh2p/][Промисел Божий vs карма]].
Якщо сказати коротко, то християни не вірять у карму, адже багато аспектів уявлень про неї прямо суперечать християнському вченню про життя і смерть, про тимчасове буття і вічність, про покликання людини. Християни вірять у Промисел Божий та можливість виправлення і покаяння, вони мають покликання та обовʼязок досягати спасіння в цьому єдиному земному житті, аби продовжити жити у вічності.
Карма з санскриту означає «дія, діяння, ритуал». У деяких релігіях Сходу (буддизмі, індуїзмі, джайнізмі та інших) карма – це «закон відплати», яким, відповідно до сукупності скоєних людиною та її предками вчинків, визначається характер її подальшого перевтілення після смерті. По суті, карма сприймається як щось негативне, що «прилипає» до людини і супроводжує її в процесі реінкарнації, тобто перевтілення, переродження душі в різних життях.  
Тут криється перша суттєва відмінність між християнством та релігіями, які сповідують реінкарнацію. Християни знають, що після тілесної смерті буття не закінчується, а є вічність, яку ми обираємо собі тут, під час земного життя, нашими вчинками й ділами. Однак, знаючи з Божого одкровення, що життя людини є унікальне, що після смерті тілесної є не якесь нове переродження, але посмертне життя душі в очікуванні майбутнього тілесного воскресіння і вічності, ми не сприймаємо думки про те, що після смерті станемо кимось іншим, ніж були, скажімо, іншою особистістю, деревом чи пташкою. Священне Писання вчить: «I як людям визначено один раз умерти, а потiм суд, так i Христос, один раз принiсши Себе в жертву, щоб взяти грiхи багатьох, вдруге явиться не для очищення грiха, а для тих, що чекають Його на спасiння» (Євр. 9: 27 – 28). Як бачимо, Писання чітко заперечує можливість багаторазових перевтілень людей та їх перетворень в іншу особистість, істоту чи предмет.
Друга суттєва відмінність полягає в питанні прощення. Оскільки у вченні індуїзму відсутній Бог, Який прощає людину, милує, дарує спасіння, то там карма набуває чисто формального, механічного характеру. Так, якщо в цьому житті люди здорові, багаті – то в минулому вони «назбирали» добру карму. Якщо ж люди страждають і хворіють, то отримують «відплату» за помилки і гріхи минулих життів. Тобто, у вченні карми гріх та покарання мають суто формальні, математичні взаємовідносини. Тут немає Милосердного Бога, Спасителя, Який викупив людські гріхи і закликає всіх до покаяння, даючи прощення тим, хто вже кається.   
Закон карми неухильно збирає все зле, зроблене людиною протягом її багатьох «перевтілень», змушуючи розплачуватись за попередні гріхи, страждати нині. Скоріш за все, вчення про карму виникло як спроба пояснити природу страждань людини, коли в цих стражданнях немає її видимої провини. Але якщо заглибитись у нього, то виходить, що закон карми певним чином «узаконює» несправедливість: адже після тілесної смерті особистість людини «розпадається», а нова, що виникла нібито внаслідок реінкарнації, не може зрозуміти, за який саме проступок вона має розплачуватись – а тому вона не може винести зі своїх страждань ніякого морального уроку. Залишається просто відчуття життєвої несправедливості і приреченості. 
Вчення про карму перетворює людину з вільної особистості на гвинтик кармічного механізму, позбавляючи її свободи волі. Людина в рамках цієї концепції стає сліпою маріонеткою. Християнство ж відкидає цю кармічну приреченість, яка зберігається у багатьох перевтіленнях, і вчить про те, що людина живе лише один раз, і що в її єдиному земному житті діє Промисел Божий, який сприяє її спасінню. 
Промисел Божий – це реалізація благої Божої волі про все, що існує на Землі у просторі й часі, він спрямовує все Боже творіння на благо, допомагає всьому доброму, присікає зло. Людину Бог створив за Своїм образом, Він з любові дарував людині великий дар свободи і ніколи не порушує його, не чинить насилля над людиною. Свобода – це завжди вибір, а вибір – це відповідальність, наслідки. Тому зло і страждання у розумінні християнства – це наслідок неправильного, хибного вибору людини, який завжди можна виправити, покаявшись і отримавши прощення від Бога. Карма ж такої можливості не дає. 
Ми як християни віримо, що всі наші вчинки, наміри, діла і навіть бездіяльність формують наше майбутнє, причому не лише після тілесної смерті, але й нині, під час земного життя. Ми вільні обирати своє майбутнє, ми не є маріонетками «долі» чи «карми». Ми є дітьми Божими. «Hе обманюйтесь: Бог зневаженим не буває. Що посiє людина, те й пожне. Хто сiє для плотi своєї, вiд плотi пожне тлiння, а хто сiє для духа, вiд духа пожне життя вiчне» (Гал. 6: 7–8). 

*** Тупість як гріх
У 1943 році, у в’язниці гестапо, пастор і мислитель Дітріх Бонгьоффер сформулював одну з найпровокативніших думок ХХ століття: тупість небезпечніша за зло. Парадоксально, але саме вона, а не цинічний умисел, найчастіше забезпечує довге й комфортне життя ідеологіям, режимам і катастрофам.
У цьому твердженні немає зверхності — лише точність. Бо тупість у розумінні Бонгьоффера — це не про низький IQ. Це не образа, не ярлик, а моральна вада, яка виникає тоді, коли людина добровільно відмовляється думати самостійно. Це не брак здатності, а брак волі.
 «Проти тупості ми безсилі. Протести не допомагають. Пояснення — марні. Факти, що суперечать упередженню, не приймаються — а якщо й приймаються, то перекручуються.»
Тупа людина щиро впевнена у своїй правоті. Її переконання зазвичай прості, зручні й добре упаковані у зрозумілі гасла. Вона не агресивна — поки не ставити під сумнів її у картину світу. Вона не зла — просто охоче стає інструментом зла в чужих руках. Бо так простіше.
І тут ми підходимо до найнебезпечнішого моменту: тупість має соціальну природу. Вона розквітає в умовах, де людину позбавляють особистої відповідальності. Де мислення замінює лояльність, а сумнів — зрада. Тупість розмножується там, де пропаганда системно витісняє критичне мислення. Де просте рішення завжди правильне, а складне — підозріле.
 «Мені сказали — я зробив. Що не так?»
Насправді — усе так. Саме так діє механізм. Так функціонує система, в якій від особистості вимагається не розуміння, а підкорення. І якщо когось у цьому ланцюзі назвати “винним”, то це не завжди буде диктатор. Часто — той, хто дозволив собі не думати.
Зі злом, як зазначає Бонгьофер, ще можна сперечатись. Його можна викрити, дати йому оцінку, накласти санкції. А от з тупістю — ні. Вона не розуміє аргументів, не визнає фактів, не чує контексту. Вона щиро вірить, що дії, які призводять до катастрофи, — це «єдино правильний шлях». Бо інші — або вороги, або нерозумні.
У нашому часі ця думка звучить особливо актуально. Вона пояснює, чому цілком розумні люди підтримують антигуманні  ідеї. Чому освічені фахівці повторюють маячню з телевізора. Чому у складних ситуаціях суспільство масово тікає у просте, готове, чужими руками розжоване.
Тому боротьба з тупістю — це не іронія інтелектуалів. Це не снобізм. Це етика виживання. Бо суспільство, яке не культивує вміння мислити, неминуче стає жертвою тих, хто чудово вміє маніпулювати тими, хто не думає.
 «Тупість — не особисте нещастя. Це інфраструктура зла.»
І якщо вам здається, що мислити стає дедалі важче, а бути тупим — дедалі безпечніше, пам’ятайте: мислення — це акт мужності. І, можливо, останній захист світла, яке хтось дуже прагне вимкнути [[https://www.facebook.com/share/p/1KT79BmG73/][Відси]]

[[https://www.facebook.com/share/p/14sx241L9bh/][Ісихазм]]
Багато задумів у серці людини, але відбудеться тільки визначене Господом. Книга притч Соломонових. 19:21
[[https://www.facebook.com/share/p/1HHUGuXM7K/][Дозвіл під час менструацій]]
[[https://www.facebook.com/reel/2239150979884559][Сімейне]]
*** Екорцизм
https://www.youtube.com/watch?v=cu_XAtRsgzU

*** Церковне
[[https://www.facebook.com/share/p/1BcgWw6zyM/][Просфори]]
[[https://www.facebook.com/100057215715956/posts/1195216012395578/][Господи, помилуй]]
[[https://www.facebook.com/100000021063759/posts/10095720300438572/][Православний фундаменталізм, Іран, Апокаліпис]]
[[https://www.facebook.com/100003328691504/posts/9573393436114851/][Нєкролог про Папу Франциска]]
[[https://www.facebook.com/100001454568857/posts/pfbid05YHy3A94HySJQTGNenCggT2i4C2ZeQfLBaSHo1b9VYGgHFkk9WcDHbGiBdb6LZKQl/?app=fbl][Жіноче священство 1]].
[[https://ecerkva.com/uk/articles/traditions/1396-zhinoche-sviashchenstvo-ta-ikonichna-pryroda-liturhii][Жіноче священство 2]]
[[https://www.facebook.com/share/p/17mJXHWxwU/][Про розарій]].
[[https://www.facebook.com/100003234403736/posts/25214040361620430/?mibextid=rS40aB7S9Ucbxw6v][Про архаїку в Церкві]].
[[https://www.facebook.com/100001973797716/posts/25119870377662076/?mibextid=rS40aB7S9Ucbxw6v][Ще трохи про еволюцію]].

** Відео
[[https://www.facebook.com/reel/887293116894766][Три етапи приходу до Бога та Його благословення]]
[[https://www.facebook.com/reel/615023639230520][Про причастя з однієї лжиці]]
[[https://www.facebook.com/reel/491140137144041][звідки взявся Бог?]]
[[https://www.facebook.com/reel/1085054693169595][Про чужу жінку]], перелюб, зраду
[[https://www.facebook.com/bar.viktor2010/videos/8763842297039891/][Tак звучала церковнослов'янська мова в Україні перед Переяславською радою 1654 року.]] Після чого почалась русифікація церковнослов'янської мови, як власне, і всіх сфер українського життя.
[[https://www.facebook.com/reel/538652065891141][Про Божі обіцянки]], заповіт увійшов у дію, бо Ісус помер
[[https://www.facebook.com/reel/555145067345518][Самодисципліна]] в пізнанні Бога, відносини з оточуючими
[[https://www.facebook.com/reel/1579070076070146][Нічого матеріального з собою не забереш]] /Єврея не похоронили в шкарпетках ;)/
[[https://www.facebook.com/100000306321536/posts/9438434479510002/][Твоє від твоїх, Тобі приносимо за всіх і за все.]]
[[https://youtube.com/shorts/TDm-qHU8l28?si=LxKOPnwD0HqWkAA5][Хто такий парафіянин?]]
[[https://www.instagram.com/reel/DC6m7NlKsZy/][Ми грішні і відділені від Бога, але є хороша новина]]
[[https://www.facebook.com/reel/509004028914985][Про хрещення дітей]]
[[https://www.facebook.com/reel/594169769687083][Різдво. Ісус пройшов усе те, що пройшли українці.]]
[[https://www.youtube.com/watch?v=Xa-vFC-hDBM][Про митаря і фарисея]] Ісусова молитва, блудного сина
[[https://art-room.com.ua/uk/kartini-ivana-ajvazovskogo/khodinnja-po-vodakh.html][Ходіння по водах Айвазовський]]
[[https://www.youtube.com/watch?v=eda4_viEetk][Зловживання вченням про божу любов]] Євангеліє процвітання
[[https://www.youtube.com/watch?v=iTnbpsy1WVQ][Важливі уроки найвідомішої притчі про блудного сина]] неділя блудного сина
[[https://www.youtube.com/watch?v=wwNS6B_Gs3g][Якщо Бог добрий, то чому ми страждаємо? • Валерій Антонюк]]
[[https://youtu.be/wXgpz3BGdGw?si=bPqtb9rU9PUZLofz][Сумніви в вірі]]. Валерій Антонюк
[[https://www.youtube.com/watch?v=dmpvkaE8nUQ][ДЕ БРАТИ СИЛИ, коли охоплює виснаження? Приклад Христа]]
[[https://www.facebook.com/reel/1113669423526613][Про тілесність та катарів]]
[[https://www.facebook.com/share/v/1BLYdzZoCY/][Що зв'яжете чи розв'яжете на Землі, те і на Небі]]
[[https://www.facebook.com/reel/2373695923025359/?mibextid=rS40aB7S9Ucbxw6v][Боже провидіння]]. Наша мета — спасіння. Навернення.
[[https://www.facebook.com/reel/1224446953056352][Комфортне християнство не плодоносить]].
[[https://www.facebook.com/reel/1740928539921334/?mibextid=rS40aB7S9Ucbxw6v][Чому важливо утримуватися від сексу до шлюбу]]
[[https://www.facebook.com/reel/699415883223046/?mibextid=rS40aB7S9Ucbxw6v][Ти не знав, на що підписався, коли прийняв Ісуса]]. Духовна боротьба Коли ж у твоє життя прийшов Ісус і Дух святий вступив у битву із твоіми гріхами.
[[https://www.facebook.com/share/p/1G3QVqY6de/][Підставити другу щоку — це підкоритися кривднику]]?
[[https://www.facebook.com/reel/1334888214198396][Екзорцизм важливий, але не так, як Таїнства]]. Забобонність про форму як джерело спасіння.

* Цитати
** Варфоломій
*** Віра та толерантність розмовляють однією мовою. Їхня абетка – свобода.
Я інколи дивуюся, як може людина лишатися байдужою до масового винищення людей в ім’я ненависті та забобонів. Все ж я глибоко переконаний, що спільноти віри спроможні – та зобов’язані – розбудити людей від цієї байдужості. Адже «права людини» - не винахід Просвітництва: вони стосуються самої сутності релігії, невіддільної від поняття релігійної свободи і терпимості. Коли ми, ті, хто вірує, мовчимо у відповідь на нетерпимість і тортури, ми перестаємо бути і вірними, і людьми. І зрозуміло, ми не є вільними. Коли ми, вірні, заплющуємо очі на приниження та дискримінацію інших – це значить, що ми не визнаємо в них образу Божого. У цю мить ми відмовляємо собі у привілеї бути вільними. Коли ми, вірні, не звертаємо уваги на страждання та муки інших, ми відмовляємося бачити себе у цих інших.
Віра та толерантність розмовляють однією мовою. Їхня абетка – свобода.
Вселенський патріарх Варфоломій. Книга "Віч-на-віч із Тайною"
** Дедюхін
*** 1
ФАРИСЕЇ: А коли ж прийде Царство Боже?
ІСУС: Непомітно. Не буде жодних знамень, крім знамення Іони. Ніхто з плакатами про Царство Боже ходити не буде. Царство Боже всередині вас є.
ОТЦІ ЦЕРКВИ (НІССКИЙ, ПАЛАМА, ІСААК СИРИН): слухайте Ісуса, живіть так, як наче ви вже в Царстві Божому, бо воно з вас починається і Церквою стверджується.
СУЧАСНІ ХРИСТИЯНИ: Тю, та до Царства Небесного лише на катафалку можна доїхати.
ЗАВІСА [[https://www.facebook.com/share/p/15rx4QVan1/][Відси]]
*** 2 Самодовольство.
Ні, не ота крива пародія на гордість, яку вам підсовують з болотяного московського ізводу. А справжнє, церковнослов’янське слово. Те, яке народжене святими людьми — учнями Кирила і Мефодія. Мовою, що гармонійно злилася з давньоукраїнською, дала коріння для наших молитов, літургій, псалмів і піснеспівів. А потім була брутально скорочена, спотворена й знівечена московською редакцією.
У справжній церковнослов’янській самодовольство — це не самозакоханість. Це повнота. Матеріальна й духовна. Це благополуччя, достаток, спокій. Це коли в тебе є все потрібне, й навіть більше — щоб поділитись.
Самодовольна людина — не лізе до сусіда воювати чи жебракувати. Вона вже наповнена.
Тому, парафіяни, будьте самодовольними.
Не гордими, а гідними.
Не пихатими, а сповненими.
Не тривожними, а мирними.
Бо хто самодоволен у Христі — той уже багатий.
Люблю самодовольних. Вони вміють по-справжньому дякувати. [[https://www.facebook.com/share/p/1BTMtVKJTB/][Відси]].
*** Свинство
Коли до нас приходить Христос, з нашої середини починають вилазити свині. Багато свиней. Легіон свиней. І ми кажемо Христу: "Господи, відійди від нас, нам хрюшек жалко, і перед людьми невдобно. Ти непоганий, проти Тебе ми нічого особисто не маємо, але іди десь за море. Чужих свиней ганяй..."
*** Вознесіння
Вітаю з Вознесінням! 
Вознесіння Христа означає що Він перебуває не на якомусь конкретному небі – над Амерікою, Росією Україною чи Коста-Рікою. Він на Небесах Небес і скрізь, поруч із кожним із нас, бо небо розпочинається там, де закінчується земля. Небо починається у наших ніг.
Також вознесіння означає, що Ісус Христос не залишає по собі на землі ніяких посередників. Для спілкування з Богом не потрібні ні папи Римські, ні патріархі, ніхто. Кожен з нас вільно може приходити до Бога, бо Він Сам сказав: «Ось я з вами до кінця віку».
Мене можуть спитати: «А для чого ж тоді потрібні священникі і храми? Для спільної молитви. Ми відокремлюємо храм із світу, що лежить у злі, освячуємо його і робимо святинею, до якої ми приходимо і очищаємо душу. 
А священник – це зовсім не посередник між людиною та Богом. Він лише слуга Божий, та посередник між Богом та людиною, який виносить Чашу для причастя вірних.
*** Манна небесна
Хочешь манны небесной? Да без проблем. Будет тебе манна мерою доброю и утрясённою. Но только для начала собирай манатки, семью, скот, бросай дом, котлы с мясом, плинфотворение и шуруй в пустыню поклониться Господу. 
И когда ты Его встретишь - манна просыпется, столько, сколько тебе нужно, не переживай. Но помни, манна - это лишь этап на пути в Землю, текущую молоком и медом. Манна - пища пустыни. Учись доверять Богу. Без этого доверия ты так навсегда в пустыне и останешься.
*** День Трійці - антивавілон
Одного разу люди, в черговий раз, захотіли "стати як боги". Тільки цього разу вони вирішили збудувати вежу до небес в місті Вавілон, щоб "зробити собі ім'я", і звеличити його. Домовилися вони про це, тому що "На всій землі була одна мова та слова одні." (Бут. 11.1). І зібралися вони, і мабуть побудували би, бо гординя людська велика, навіть не до небес, а набагато вище. Але тоді Бог зійшов і "змішав там їхні мови, щоб один не розумів мови іншого" (Бут.11.7), щоб упокорити гординю їх.
Дуже важливо розуміти, що Господь змішує мову, а не просто кожній групі людей велить розмовляти тією чи іншою мовою. У Вавилоні змішуються поняття і тоді люди перестають розуміти один одного. І ось саме з причини цих "незрозумілостей" вежа перестає будуватися. І справді, як можна щось побудувати, коли, наприклад, прораб каже "замішуй розчин", а робочий починає тягати цеглу?
Мова кожного народу виникає потім - коли люди її знаходять, цю спільну мову, коли навчаються вгамовувати свою гординю і домовлятися один з одним ...
І от через тисячи років після Вавілонського стовпотворіння. Через десять днів після Вознесіння Христового на небо, через п’ятдесят днів після Його Воскресіння, сталася велична подія хрещення Духом Святим святих апостолів і першої Христової церкви. Це був день єврейського свята П’ятидесятниці, на спомин встановлення Синайського законодавства. В це свято перша Христова громада, в кількості ста двадцять душ, на чолі з Божою Матір'ю і апостолами, зібралась помолитися в світлиці. Була 9-та година ранку. І от почувся шум з неба, ніби від великого буйного вітру, і цей великий вихор — ознака взагалі перетворення, відживлення в природі — сповнив увесь дім, де вони сиділи, і над кожним з них з’явились і зупинились ніби вогненні язики, і всі вірні відчули великий запал у душі, сповнились Духом Святим, вийшли на дах того дому і почали вславляти різними мовами величність Божу, як Дух давав їм промовляти. Від серця їхнього, силою Святого Духа, забили джерела води живої, забили й вже не припиняться, не виснажаться по віки. Так сталось Зшестя Святого Духа на апостолів і першу Христову церкву, ця найвища Божа благодать, що діє в церкві. "Несподівано зчинився шум із неба, ніби буря раптова зірвалася" (Діян. 2.2) дивні бородаті Галілейські дядьки запалилися вогнем Святого Духа, і заговорили багатьма різними мовами. "Коли стався цей шум, зібрався народ, і прийшов в сум'яття, бо кожний чув них їхньою власною мовою." (Діян. 2.6)
У цей день Господь підкреслив святість кожної мови і показав кожному народові шлях до Неба Небес.
Слава Богу, минули ті часи, коли українська мова зазнавала гонінь. Коли її гнали із Церкви, із школи та звідусіль. Чому так було? Тому що бажали поневолити нашу Церкву, примусити служити її своїм, а не Божим, інтересам, тому що бажали знищити наш народ. Але як Христос воскрес, як кожного року земля уквітчується травами, квітами та зеленім листям, так і наша розквітає і мова, і Церква, і народ наш, не зважаючи ні на що. Як сходження Святого Духа на апостолів, сповнило їх силою з неба, так благодаттю Того ж Духа надихається і наш народ.
Лише на вірі в Бога у Святій Тройці можуть вирости діла, що доведуть нас до вічного життя. І коли ми на свято Тройці вбираємо свої хати зеленю, клечанням, квітами, цим ми виявляємо, що Пресвята Трійця є наша вічна, невмируща надія на життя вічне. Свіже зелене клечання, свіжі живі квіти, є ознакою життя невмирущого. Отже тільки на християнській вірі в Святу Трійцю вічно цвістиме надія на життя вічне і дасть плоди достойні цього життя. А коли листя та квіти на дереві не ростуть, що це значить? Це значить, що корінь в нього нездоровий, або мертвий. А коли на вірі в Пресвяту Трійцю не ростуть добрі діла, що це означає? Не інакше, як те, що Христову віру в собі чоловік пригнітив або й зовсім омертвів.
Господь нам дарує віру, благодать, і Духа Свого Животворчого. Господь дарує нам життя і сили. І лиш від нас самих залежить що ми будемо робити з Його дарами - будемо розквітати, чи будувати чергову безглузду та безумну імперську вавілонську вежу. А для тих, хто і далі будує дурні вежі, Господь і сьогодні сходить і змішує мови, люди перестають розуміти один одного, та нічого доброго в них не виходить.
Ми будуємо на істинній вірі, а значить Господь обов'язково дарує нам розуміння істинних змістів. [[https://www.facebook.com/share/p/16sZPYTTxX/][Відси]]
*** Неділя сліпонародженого
Христос дивиться на сліпонародженого і... плює на землю перед ним. При цьому Він промовляє: «Я світло для світу». 
Той випадок, коли слова явно розходяться з ділом. Далі — більше. Ісус бере багнюку, котра утворилася з глини і Його слини, та цим брудом маже очі каліці, а потім посилає того вмиватися. Жодним чином не обмовившись про зцілення, лише згадавши, що Він є світлом і діла Його — світло. 
Здивовані всі, окрім Ісуса і сліпця. Обидва — порушники суботи, закону та громадського спокою.
У суботу було заборонено лікувати.
У суботу було заборонено місити.
У суботу було заборонено мазати очі.
У суботу було заборонено використовувати слину.
У суботу було заборонено ходити більше 1 км. Відстань від храму до купальні Силоам була більшою.
Про зцілення сліпонародженого нам розповідає 9 глава Євангелія від Іоана. При цьому саме зцілення займає лише два вірші, а осудження, протиріччя, та сперечання — решта тридцять девʼять. 
Дія та благодать Бога завжди незвична, провокативна, скандальна, неоднозначна. Він і сьогодні готовий творити цей світ, з нашою допомогою. 
А вже відобразяться у наших сліпих очах розіпʼяті нами птахи, небеса, та закривавлені, звалені на купу дерева з повішеними на них мрійниками. Або очі наші будуть готові прийняти «бруд» від Господа, а ноги порушити загальні норми, щоби піти до святої води, вмитися, стати співтворцем власних очей та бачити не тільки до обріїв, а набагато далі — у вічність та радість. Все залежить від нас. [[https://www.facebook.com/share/p/1AsdCd7h8s/][Відси]]
*** Не втратити Бога за обрядовірство
Ходиш до храму? Що ж, тепер найважче — не втратити Бога.
Бо багато хто приходить до Церкви — і губиться в деталях. Де повертатися, як тримати пальці, який пасок "канонічний", яка спідниця "достатньо благочестива", яка зачіска не спокушає. І починається храмова гімнастика з елементами дресс-коду. А серце десь позаду.
Так от. Це не християнство.
Це — релігійна підміна. Те саме, з чого Ісус виганяв торговців з Храму, сварився з фарисеями і розповідав страшні притчі. Бо обряд без серця — це ідолопоклонство. Це коли ти замість живого Бога поклоняєшся формі.
І питаєш, як правильно: так чи так? А Христос каже: «Оце є діло Боже, щоб ви вірували в Того, Кого Він послав» (Ів. 6:29).
Не "розставляли свічки по фен-шую", а вірували, жили в довірі, у стосунках, у любові.
Бо віра — це не хреститися по шаблону, а жива єдність із Тим, Хто тебе полюбив першим. Це страх втратити любов. Загасити живий вогонь, і залишитись з димом.
Хочеш знати, чи ти на правильному шляху? Ось критерій: "Любов довготерпить, милосердствує, не заздрить, не величається, не надимається..." (1Кор.13)
Оце — твій щоденник духовного життя. Не вбрання, не суворість, не пафос. А любов.
Якщо віра не веде до любові — вона веде в інше місце.
Християнин — це не той, хто правильно перехрестився. А той, в кому живе Христос. 
Страшно не переплутати устав поклониів — Бог не образиться. 
Страшно знати купу молитов  і при цьому зневажати ближнього. Страшно служити ідолу ритуалу.
Ходи в храм. Але головне — не просто входь у двері будівлі, а входь у Життя. У Царство Любові.
І там не питають, скільки разів ти був на вечірні. Там питають, кого ти навчив любити і кому ти себе приніс в жертву любові. /Див. схоже у Собко/
*** [[https://www.facebook.com/share/p/1CqsW73crQ/][Як не заразитися злом]]
Ми маємо бути сонцем
Хто живе заради боротьби з ворогом — зацікавлений у тому, щоб ворог залишався живим.
Не варто жити заради боротьби з росіянами.
Не варто жити заради боротьби з московським сатанатом.
Не варто жити заради боротьби з нашою гидкою владою.
Не варто жити заради боротьби з дияволом.
Так, усі вони вороги. Але наше життя — не про них.
Ми живемо не "проти", а заради.
Заради царювання в Царстві, яке вже дароване нам Богом. Заради любові.
Наше Царство — не в ненависті, а у світлі. Не в прокльонах, а у славі.
Ми маємо бути не тінню ворога, а сонцем, що розтоплює його, як росу на світанку.
“Якщо Христос у тобі — ти весь стаєш світлом;  якщо ж у тобі немає світла —
то даремно ти думаєш, що бачиш.”
Симеон Новий Богослов
Світити. Навіть тоді, коли темрява щільнішає.
Бо наше завдання — не перемагати тьму, а бути світлом. /Див. схоже у Собко/
*** [[https://www.facebook.com/share/p/1a5rz6jw7f/][Покаяння — єдиний шлях до Христа]].
Покаяння — єдиний шлях до Христа.
Не від розуму ми йдемо до Нього — інакше академії наук давно б стали храмами.
Не від насолоди — інакше гедоністи співали б псалми. Але їхні співи — це попса та сморід.
І навіть не від страждання — інакше лікарні й тюрми були б переповнені святими. Але біль без покаяння тільки озлоблює.
Є лише одне. Покаяння.
Зміна свідомості.
Відчуття дерева, біля кореня якого вже піднято сокиру.
Відчуття останніх днів.
*** [[https://www.facebook.com/share/p/16R2wb7UKM/][Царство Боже вже тут]].
Мк. 9:1:
«І сказав їм: Істинно кажу вам: є деякі з тих, що стоять тут, які не скуштують смерті, доки не побачать Царства Божого, що прийшло в силі».
Царство Боже — не десь у далеких світах і не лише в майбутньому житті. Христос каже: "деякі з вас побачать Його вже зараз»". І справді — вже через кілька днів троє апостолів стали свідками Преображення. Вони побачили не лише Ісуса-Учителя, а Господа, Який сяє світлом вічності.
Царство Боже — це явлення Божої сили в нашому теперішньому житті. Воно починається там, де серце довіряє Богові більше, ніж обставинам. Там, де людина не просто чекає раю після смерті, а вже тут живе інакше: з правдою, з любов’ю, з мужністю.
Коли ми уникаємо гріха, то робимо це не тому, що хтось заборонив чи покарає, а тому, що гріх закриває нам очі на це світло. Він робить нас сліпими до Царства, яке вже прийшло в силі.
Учні побачили славу Христа на горі. Ми бачимо Його в Євхаристії, у молитві, в житті Церкви. Але щоб це світло справді відкрилося, треба ступити за межу свого страху, своєї звички, своєї "маленької зони комфорту". Бо лише так ми відчуваємо силу Божого Царства, яке приходить.
Царство Боже — це не казка на потім. Це сила, що вже діє.
Питання тільки одне: чи готові ми жити так, щоб бачити Його зараз?
*** [[https://www.facebook.com/share/p/1GujBFf8fs/][Духовність]].
Духовність — це не про те, щоб стояти на амвоні й розповідати, як усім треба молитися день і ніч.
Це про те, щоб варити борщ і не перетворювати його на отруту своєю злобою.
Це про те, щоб підмітати підлогу та не обмітати людей язиком.
Це про те, щоб свердлити перфоратором стіни, а не вуха ближнього.
І, до речі.
Ми, священники, часто не зовсім духовні.
Пристрасті у монастирях і при великих храмах інколи сильніші, ніж у вчительських колективах.
Працювати руками — ще те завдання для попа.  Апостоли Павли з нас, скажімо прямо, кепські.
Єдине, що нам справді вдається, — це причастя на кожній літургії.
І все.
А так - ні вигляду,  ні величі.
Просто духовність - це не пафосні промови, а життя перед Богом. Щомиті.
*** [[https://www.facebook.com/share/p/1CzPVSWMa4/][Убогі духом]].
"Блаженні нищі духом"
Нищі духом — це не ті, кого принизили.
Це ті, хто сам відмовився носити на шиї золотий медальйон із написом «Я головний».
Горді живуть у постійному ремонті власного его.
А «нищі духом» спокійно обходяться без цього бетону.
Тому небеса відкриваються саме їм — просто в них немає зайвого багажу.
*** [[https://www.facebook.com/share/p/1DTLR6U2EG/][Проповідь на притчу про таланти (Мф. 25:14–30)]].
Притча про таланти — це не просто розповідь про гроші чи здібності. Це пророцтво про наше життя у світлі Царства Божого. Господь показує, що не потрібно жити у вузькому колі своєї суб’єктивності, а необхідно відкритися на реальність Божу, що перевищує всі наші уявлення.
Господь закликає перевищити іманентність суб’єктивності трансцендентністю об’єктивності. Суб’єктивно ми бачимо лише один талант — шматок срібла, якусь здібність, малу силу. І нам здається, що це й є реальність. Але це лише видимість. Реальність — не наша слабкість і не наш страх. Реальність — це сто тисяч талантів. Реальність — це радість Господа нашого. Реальність — це Царство Небесне, яке вже прийшло в силі і вже всередині нас.
Апостол Павло каже: «Віра є здійснення очікуваного і впевненість у невидимому» (Євр. 11:1). І ось — віра це завжди опозиція реальності до видимості. Бо видимість — це війна, хвороби, ненависть, зневіра. Але все це — ілюзія, тінь, пил. Справжнє — це те, що дав нам Господь: таланти, свободу, гідність дітей Божих, нове ім’я, написане на камені, ім’я переможців.
Чому ж один раб закопав талант? Бо він боявся. А боягуз завжди живе у межах суб’єктивного, у вузькому колі видимості. Боягуз опирається лише на знання, на свій погляд, на власну логіку. Він не наважується зробити крок у вічність. І тому закопує талант у землю, ховає свободу в буденність, міняє царську гідність на безпечну посередність.
Але Господь нас закликає не боятися. Бо Бог не карає за помилки. Навпаки: Господь радіє кожній нашій спробі жити Царством. Єдина справжня помилка — це перестати шукати Бога, закопати талант, втратити гідність, віддати свободу страху. За це не Господь карає, — людина сама зачиняє себе у темряві, сама позбавляє себе світла.
Тож не бійтеся помилок. На нашому шляху можуть бути і крадії, і розбійники, і росіяни. Але найбільша небезпека — це боягузтво. Бо боягузи не входять у Царство, їхня доля — в озері вогняному, як каже Святе Письмо (Одкр. 21:8).
А ті, хто ризикує жити по-справжньому, ті, хто виходить за межі своєї суб’єктивності і вірить Божій реальності — ті входять у радість Господа.
Отже, Господь кличе кожного з нас: не закопуй свій талант, не втрать свою царську гідність. Перевищи іманентність суб’єктивності трансцендентністю об’єктивності. Бо справжня реальність — це Царство Боже, і воно вже серед нас.
Амінь.
*** [[https://www.facebook.com/share/p/1CGC4ZmAtw/?mibextid=rS40aB7S9Ucbxw6v][Бути насиченим життям — означає бути сповненим Богом]].
Бути насиченим життям — означає бути сповненим Богом.
У Старому Завіті про патріархів часто сказано:
"І помер, наситившись днями" (Бут. 35:29).
Звучить просто. Але якщо вдуматися — хіба можна насититися життям?
Ми завжди прагнемо ще трохи: ще подих, ще зустріч, ще мить.
І все ж Ісаак, Авраам, Яків — помирають насиченими.
Наче вони справді отримали все, що потрібно.
Не тому, що прожили "успішно".
А тому, що прожили з Богом.
Святий Іриней Ліонський каже:
"Слава Божа — це людина, сповнена життя".
А життя — це не просто дихання.
Це Бог у нас.
Бути насиченим життям — означає бути наповненим Ним, так, що вже немає порожнечі, страху, браку.
Апостол Павло називає це просто:
"Уже не я живу, але живе в мені Христос".
Той, хто наповнений Богом,
не живе з остраху перед смертю —
бо вже носить у собі Вічність.
І в цьому найвища хвала для людини:
завершити шлях не виснаженим,
а "насиченим життям"
тобто Богом.
 Бо тільки Той, Хто є Життям,
 може по-справжньому наситити
*** [[https://www.facebook.com/share/p/17EdNMWVgW/][Бог освячує нас]].
Не ми освячуємо Бога — Він освячує нас.
Ми не додаємо Йому слави — він вливає Свою славу в нас.
Ми не робимо Його святішим — Він робить святішими нас, доторкаючись до нашої брудної, втомленої людяності. 
Не Петро прощає Бога за біль зради, а Бог прощає його і повертає в життя. 
Святість — це не людська заслуга, а відповідь на Боже “Чи любиш Мене?”.
Ми лише дозволяємо Йому освятити нас, дозволяємо влитися у нас,
як ріка в сухе русло.
Не ми перетворюємо Хліб у Тіло —
Хліб перетворює нас у Тіло Христове.
Не ми робимо Бога присутнім —
а Він робить нас живими.
Святість — не вершина, а вмістимість.
Той, хто дозволяє Богові увійти — уже освячений.
** Собко
*** [[https://www.facebook.com/share/p/1Fjbmtx1EC/?mibextid=rS40aB7S9Ucbxw6v][Доросла віра == жертва любові]].
Доросла віра - це не казка для втіхи, а шлях, який потребує мужності, рішучості й правди перед власною совістю. Коли ми свідомо переступаємо Божі Заповіді, ми відрікаємося від світла, добровільно занурюючись у тінь. І тоді навіть молитви стають холодними, а серце - кам’яним.
Христос не кличе нас у розкіш, а в жертву любові. Він не обіцяє зручного шляху, а показує вузьку стежину, що веде до Царства Небесного. Бо справжня свобода - не у вседозволеності, а у вмінні сказати гріху «ні».
Тільки той, хто відкине самолюбство і піднесе серце в покаянні, зрозуміє, що заповіді - це не кайдани, а крила. Вони не обмежують, а навпаки - зберігають душу від падіння. І тоді страх Божий стає не жахом, а благоговінням перед Любов’ю, Яка терпляче чекає нашого повернення.
Ми не створені для тимчасових утіх - ми створені для вічності. І кожен день, коли ми обираємо добро замість гріха, стає кроком назустріч Отцю, Який завжди виходить нам назустріч.
*** [[https://www.facebook.com/100063702520939/posts/1481853503948053/?mibextid=rS40aB7S9Ucbxw6v][Довіра]].
Одне діло вірити, що Бог існує, а зовсім інше, довіряти Йому кожен подих свого життя. Звичайна віра часто зупиняється на словах і обрядах, а віра святих живе в серці й вчинках. Вони не просто говорили «Господи, вірую», вони жили так, ніби Бог справді керує всім, навіть тоді, коли світ валився під ногами.
Святі вірили не в чудеса, а Тому, Хто їх творить. Вони приймали біль як частину шляху, знали, що навіть скорбота може стати благословенням, якщо пройти її з Богом. І тому їхня віра була незламною, не тому, що вони не мали страхів, а тому, що знали: Бог не зрадить, навіть якщо все інше впаде.
Мені здається, що саме цього бракує нам, не просто вірити в Бога, а навчитися вірити Богу. Його словам, Його волі, Його любові до нас. Це віра, яка не шукає доказів, бо вже знайшла довіру.
**** Мета Бога не прибрати перешкодинавчити нас йти разом з Ним крізь них із миром у серці.
Коли довіряєш Богові, навіть найтемніші дні наповнюються сенсом. Те, що раніше здавалося болем і втратою, раптом починає світитися зсередини, як частина великого плану, який ти просто ще не розумів. І тоді труднощі перестають бути ворогами, бо через них Бог формує твою силу, терпіння й віру.
Ми часто просимо: «Господи, забери мій тягар», а Він відповідає інакше: «Я допоможу тобі його нести». Бо Його шлях, не в тому, щоб прибрати перешкоди, а в тому, щоб навчити нас йти крізь них із миром у серці. І з кожним кроком душа міцніє, очищається, зростає, і саме тоді труднощі стають благословенням.
Довіра до Бога, це не втеча від реальності, а найвищий прояв сили. Це коли ти йдеш, навіть не бачачи дороги, але знаєш: Він веде. І рано чи пізно ти озирнешся й скажеш: «Як добре, що все було саме так. Як добре, що я не здався». Бо той, хто довірив Богові своє життя, уже не може програти, він іде дорогою благодаті.
*** Не осуджуй ближнього: тобі гріх його відомий, а покаяння невідоме.
Бо що ти бачиш? Падіння. А Господь, Який гляне глибше – бачить боротьбу, сльози вночі, стогін серця, прагнення змін.
Ми надто часто дивимось на людину через призму її слабкостей, забуваючи, скільки разів самі падали, скільки разів нас піднімала благодать. А ще — як лагідно Бог ставиться до нас, навіть коли ми не варті ні Його прощення, ні Його милості.
Серце брата чи сестри — це храм, в якому іде таємнича праця Святого Духа. І якщо ти не бачиш диму кадила, це ще не означає, що там немає вогню.
Тому благословляй, а не осуджуй. Молися, а не шепочи осудливих слів. Плач за гріхи свої, а не за чужі провини. І тоді милість Божа накриє тебе, як роса з неба — тихо, лагідно, зцілюючи.
Бо не судом ми спасемося, а любов’ю. [[https://www.facebook.com/share/p/16BHtuhhBf/][Відси]].
*** [[https://www.facebook.com/100063702520939/posts/1460573082742762/?mibextid=rS40aB7S9Ucbxw6v][Будьте обережні з чужими душами, бережіть інших]].
Ставтеся один до одного дуже дбайливо!!! Бо ми не знаємо, через що проходить серце поруч. Людина може усміхатись, а всередині мовчки кричати від болю. Може жартувати, а насправді ледве тримається, щоб не розпастися на шматки.
Дбайливість – це мова любові, якою розуміють навіть ті, що втратили віру у добро. Це простий погляд із теплом, слово підтримки, лагідний дотик, тиша поруч, коли не треба нічого пояснювати.
Ми всі надто крихкі, щоб ранити одне одного байдужістю. Тому будьте обережні з чужими душами. У кожній із них живе Божий вогонь – його легко згасити, але як же важко потім розпалити знову.
Нехай наші серця стануть притулком для втомлених, а не мечем, що ранить. І тоді Бог, дивлячись на нас, скаже: «Ось, діти Мої, що люблять по-справжньому».
*** [[https://www.facebook.com/share/p/16CDLxhq7f/][Сум'яття, суєта та спокій]]
Як же часто ми несвідомо заражаємо інших своїм внутрішнім сум’яттям… Біжимо, метушимось, перебиваємо одне одного, говоримо уривчасто, нервово, наче все горить і все вимагає негайного вирішення. Але чи дійсно горить?
Якби тільки ми могли зупинитися. Перехреститися. Зробити глибокий подих і визнати: «Господи, без Тебе я нічого не зможу. Допоможи мені бути миром там, де метушня. Світлом там, де хаос. Тишею там, де гримить душевна буря».
Спокій починається зсередини. І якщо Христос живе в нашому серці, то з Ним приходить лагідність, розсудливість і той таємничий мир, який не залежить ні від подій, ні від людей довкола.
Дай нам, Боже, навчитись бути спокійними навіть тоді, коли світ навколо гуде, коли обставини лякають, коли інші скидають на нас своє хвилювання. Щоб наш спокій став для когось порятунком. Щоб наша тиша заглушила чиїсь тривоги. Щоб через нас Ти, Господи, торкнувся зранених сердець.
Навчи нас нести мир. Навчи нас бути Твоїм спокоєм.
*** [[https://www.facebook.com/100063702520939/posts/1340399058093499/][Біль, випробування та щастя]]
Життя не починається «потім», коли все налагодиться. Воно тут і тепер - з усіма болями, випробуваннями, втомою, але й з усім тим світлом, яке ми можемо дарувати й приймати. Стане краще не тоді, коли зміниться обставина, а коли зміниться серце.
Щастя - це не відсутність проблем. Це присутність вдячності. Це коли попри біль ти бачиш сенс. Попри втому - не втрачаєш надії. Попри втрати - любиш ще дужче.
Навчись бути щасливим у сльозах. Навчись благословляти Бога в бурі. Бо справжнє щастя - це внутрішній дім, де живе Христос. І якщо Він із тобою - ти не спізнився. Ти вже встиг.
**** [[https://www.facebook.com/100063702520939/posts/1481693833964020/?mibextid=rS40aB7S9Ucbxw6v][Чому Бог виховує через біль]].
Господь іноді змушений торкнутися нашого життя болем, щоб розтопити наш лід, зруйнувати облуду самодостатності. Бо коли в нас усе гаразд, ми швидко забуваємо, Хто дає нам саме це «гаразд». Ми віддаляємось, наче діти, яким на мить дозволили вийти у двір без нагляду, і вони одразу ж тікають подалі, аби хоч трохи відчути себе вільними. Але Бог не карає, Він виховує.
Через випробування Він очищає наші очі, щоб ми нарешті побачили Його, а не лише свої болі й втрати. І коли, знесилені, ми падаємо навколішки, тоді вперше по-справжньому чуємо Його голос у глибині серця.
Це страшно, коли з нас здирають стару шкіру, коли все, на що ми спиралися, руйнується, коли залишаєшся сам у темряві. Але саме там, у тій тиші й самотності, народжується нове життя. Саме там Бог формує з уламків нашої гордості щось справжнє, людину, яка вже не тікає, а залишається поруч, навіть коли боляче.
Бо коли вже нема до кого йти, залишається лише Він. І це найбільше щастя, яке може народитися з болю.
*** Коли ти не вивозиш
Душа починає відчувати полегшення, коли перестає тягнути на собі тягар усього світу і визнає, що є Той, Хто керує всім. Бо хіба може людина змінити те, що від неї не залежить? Хіба може вона прискорити чи сповільнити хід Божого промислу? Усе, що від нас вимагається, - це смирення, довіра і молитва.
Коли серце віддає своє життя Господу, воно наче знаходить прихисток у міцній скелі. Вітер земних турбот і хвилі тривог більше не топлять, бо душа знає: «Господь - моя твердиня і захист». І тоді будь-яке лихо перетворюється на урок, будь-яка скорбота - на сходинку до Неба.
Тільки в Бозі знаходить душа справжній спокій. І коли ми, замість того щоб боротися з кожною хвилинною бурею, вчимося покладатися на Його любов і милість, тоді вже не ми несемо життя, а Господь несе нас у Своїх долонях. І це найбільший мир, який може пізнати людина.
*** [[https://www.facebook.com/share/p/17fTFnyGyU/][Бог знає про твої труднощі]].
Варто бачити в усьому руку Божу.  Не нарікати, не порівнювати, не засмучуватись, а приймати все, як дар, навіть те, що болить.  Бо Господь не дає нічого даремно.  У кожному випробуванні Він ховає зерно благодаті, у кожному болі – можливість очищення, у кожній радості – нагадування, що Його любов жива.
Коли в тобі є ця віра, ти стаєш непохитним.  Бо хто впізнав у всьому Божу присутність, того вже не зламають земні бурі.  Він може втратити майно, здоров’я, навіть друзів, але не втратить спокою.  Бо знає, що головне – це не те, що маєш, а Кому ти належиш.
Бог не обіцяє, що життя буде легким.  Але обіцяє, що буде поруч завжди.  І коли ми приймаємо цю істину, тоді навіть найважчі дні наповнюються світлом.  Тоді ми починаємо бачити диво в кожній дрібниці – у ранковому сонці, у слові дитини, у запаху хліба, у тиші вечора.  І це стає нашою молитвою – тихою, але справжньою.
Щастя не десь там, за межами досяжного.  Воно у серці, яке дякує.  У душі, яка вміє сказати: «Господи, нехай буде воля Твоя».  І тоді все, що раніше здавалося тягарем, перетворюється на благословення.  Бо коли живеш із Богом, навіть хрест стає легшим, бо несеш його не сам.
*** [[https://www.facebook.com/100063702520939/posts/1441377907995613/?mibextid=rS40aB7S9Ucbxw6v][Присутність Бога — це твій внутрішній мир]].
Якщо твоє серце буде тихим і відкрите для Бога, то навіть серед бурі навколо тебе збережеться внутрішній мир. Коли душа наповнена спокоєм, тоді люди, події й навіть випробування приходять у правильний час і стають частиною дороги, яку Господь приготував.
Не потрібно бігти за тим, що належить нам від Бога. Треба тільки відкритися Його волі, довіритися і навчитися зберігати мир усередині. Бо справжній скарб не у тому, що ми назбираємо в житті, а у тому, що не зможе забрати жодна буря - в мирі, який дає Христос.
Там, де спокій душі, там завжди відчувається Його присутність. І тоді все інше саме приходить - як благословення.
*** Пережити труднощі і радість
Занепокоєння - це злодій, який краде у нас здатність радіти життю.
Це мов тінь, яка лягає на серце, навіть коли навколо світить сонце.
Воно підкрадається нишком - через думки, страхи, недовіру до Бога.
А потім сідає важким каменем на груди, не даючи вільно дихати.
Але ж Господь сказав: «Не журіться про завтрашній день».
Бо кожен день має досить власного клопоту,
а майбутнє належить не нам - а Йому, Хранителю часу.
Якщо довіряємо Йому своє сьогодні, то й завтра стане світлішим.
Навіщо носити тягар, який Господь готовий зняти?
Навіщо тримати в руках кермо, якщо очі наші сліпі,
а Його - бачать усе наперед?
Віддай усе Йому - і тривога відступить, як ніч перед світанком.
Бо мир приходить не тоді, коли зникають проблеми,
а тоді, коли серце каже: «Боже, я з Тобою, а Ти - зі мною».
І стає легко.
Так легко, що хочеться жити, вірити й любити.
*** [[https://www.facebook.com/100063702520939/posts/1337506215049450/][Хвали Бога]]
В щасливі хвилини - хвали Бога.
У важкі - ШУКАЙ БОГА.
У тихі - поклоняйся Богові.
У хвилини болю - довіряй БОГУ.
Кожну хвилину - дякуй Богові.
Бо кожна мить твого життя
з Його руки - мов свіже хлібне тісто:
іноді гірке, іноді солодке,
але завжди - на спасіння, не на згубу.
Навіть коли сльози течуть,
Він рахує кожну.
Навіть коли мовчить,
Він поруч - ближче, ніж дихання.
Коли зіб’єшся з дороги -
не бійся повернутися.
Його любов не знає втоми,
Його милість - без дна і без меж.
Тож не зупиняйся в хвалі,
не вагайся в подяці,
і навіть коли серце стогне -
кажи: "Слава Тобі, Господи, що живу!"
*** [[https://www.facebook.com/100063702520939/posts/1338327368300668/][Занепокоєння]]
Занепокоєння - це злодій, який краде у нас здатність радіти життю.
Це мов тінь, яка лягає на серце, навіть коли навколо світить сонце.
Воно підкрадається нишком - через думки, страхи, недовіру до Бога.
А потім сідає важким каменем на груди, не даючи вільно дихати.
Але ж Господь сказав: «Не журіться про завтрашній день».
Бо кожен день має досить власного клопоту,
а майбутнє належить не нам - а Йому, Хранителю часу.
Якщо довіряємо Йому своє сьогодні, то й завтра стане світлішим.
Навіщо носити тягар, який Господь готовий зняти?
Навіщо тримати в руках кермо, якщо очі наші сліпі,
а Його - бачать усе наперед?
Віддай усе Йому - і тривога відступить, як ніч перед світанком.
Бо мир приходить не тоді, коли зникають проблеми,
а тоді, коли серце каже: «Боже, я з Тобою, а Ти - зі мною».
І стає легко.
Так легко, що хочеться жити, вірити й любити.
*** Справжня віра формується у труднощах
Коли прийде смуток, не поспішай з ним боротися, прийми його спокійно, як гостя, що нагадує про твою людяність і потребу в Бозі. Бо навіть у журбі є користь: вона очищує серце, спонукає до молитви, робить нас ближчими до тих, хто страждає. Так і формується справжня віра - не у хвилини спокою, а у хвилини боротьби.
Не шукай щастя у мінливих речах. Усе зовнішнє - лише тінь. Сьогодні воно є, завтра - нема. Але внутрішній світ, спокій і віра не зникають, якщо живеш із Богом. Коли серце в Ньому укорінене, жодна буря не вирве тебе з ґрунту.
Живи просто. Радій малому. Дякуй за хліб і за працю, за сонце і дощ, за людей поруч і навіть за тих, хто не розуміє тебе. Бо кожен - частина твого шляху до Неба.
І пам’ятай: усе, що відбувається, Бог допускає для твого зміцнення. Якщо боляче - значить, Він лікує. Якщо важко - значить, тренує твою віру. Якщо спокійно - значить, дав перепочинок.
Отож, не нарікай і не лякайся. Приймай усе як послання любові. Бо у світі, де панує Бог, нічого випадкового немає.
*** [[https://www.facebook.com/100063702520939/posts/1480860467380690/?mibextid=rS40aB7S9Ucbxw6v][Смирення як досвід любові]].
Саме в скорботі людина починає бачити правду про себе. Коли з тебе знімають усі зовнішні прикраси, коли нічого вже не тримає і не радує, тоді серце стає голим перед Богом. І ось тоді Господь починає творити в ньому чудо - очищати, лікувати, наповнювати любов’ю.
Без скорботи не буває істинного смирення, а без смирення неможлива любов. Тільки той, хто сам пройшов через біль, здатен по-справжньому співчувати іншому. Той, хто плакав, розуміє чужі сльози. Той, хто падав, уміє підняти ближнього.
Бог не карає нас стражданнями - Він виховує нас через них. Він вчить бачити в темряві Його світло, у втраті - Його присутність, у безсиллі - Його силу. І коли душа, пройшовши через усе це, знову починає довіряти, дякувати, любити - тоді на неї сходить справжня благодать, спокійна і тиха, як ранкове світло після бурі.
Тому не бійся скорбот. Прийми їх, як шлях до очищення, як благословення. Бо через біль Господь формує у нас серце, здатне любити по-справжньому.
*** Спори
**** [[https://www.facebook.com/share/p/1FnQ2drKFZ/][Не спорь забагато]].
Життя коротке, і воно не варте того, щоб проживати його в роздратуванні, у доказах, у безкінечних спробах пояснити себе тим, хто все одно не почує. З роками приходить розуміння, що спокій дорожчий за будь-яку правоту, а внутрішня рівновага цінніша за всі перемоги в суперечках.
Бережи своє серце від дрібниць, які не заслуговують навіть хвилини твого життя. Люди, які хочуть тебе зрозуміти, зрозуміють і без пояснень. А ті, хто шукає, до чого причепитися, знайдуть привід навіть у твоїй тиші. Тому просто живи спокійно. Вибирай тишу, добро і простоту.
Нехай твої нерви будуть у мирі, думки – у світлі, а серце – у Бозі. Бо саме тоді приходить справжнє щастя: коли нічого не треба доводити, коли живеш чесно, без надриву, без поспіху. Коли приймаєш життя як дар і кожен день як ще одну можливість дихати, любити і дякувати.
Бережи свої нерви – це означає, бережи свою душу.
*** ЛЮБОВ
**** [[https://www.facebook.com/100063702520939/posts/1343199141146824/][1]]
Любов - це не блискавка, яка вдаряє раптово. Це вогник, який запалюється тихо і горить усе яскравіше, коли його плекають. Коли ти слухаєш її не для відповіді, а для того, щоб зрозуміти. Коли вона чекає тебе не тому, що мусить, а тому, що хоче. Коли ваші мовчання поруч тепліші за слова.
Це - довгі розмови до ночі, щирий сміх, коли вам разом весело, сльози, які не соромно показати, і молитви, які ви шепочете в тиші, тримаючись за руки. Це коли йдете через труднощі не кожен окремо, а разом, однією командою. Це коли не шукаєш кращого, бо знаєш - твоє вже поруч.
Справжнє кохання виростає не тоді, коли все ідеально, а коли двоє разом справляються з неідеальністю. І коли ти розумієш: я поруч не тому, що зручно, а тому, що обрав.
Бо любов - це завжди про вибір. Щоденний. Осмислений. Серцем.
**** [[https://www.facebook.com/100063702520939/posts/1342553421211396/][2]]
Має значення тільки те, що ти робиш.
А говорити можна все, що завгодно.
Бо слова - як вітер: легкі, безплотні,
Їх легко вимовити, важко втілити.
А вчинки - як камінь: залишають слід.
Вони свідчать про серце краще за тисячу обіцянок.
Можеш говорити про любов -
Але якщо не простягнеш руки, коли хтось падає,
Хіба то любов?
Можеш говорити про віру -
Але якщо зрадиш у важку хвилину,
Чи віриш ти насправді?..
Життя вимірюється не словами,
А чашкою води, поданою в ім’я любові.
Поглядом, що підтримав.
Молитвою, що була невидима іншим.
Тільки те, що робиш -
Залишиться назавжди.
Усе інше - розвіється, як дим на вітрі.
**** [[https://www.facebook.com/share/p/16Wx9szsKq/][3]]
Любов чоловіка має бути сильною, мов скеля, але м’якою, як оксамит. Це не слабкість, коли ти перший просиш пробачення. Це не приниження, коли поступаєшся для миру. Це – сила, яка береже, а не ламає. Сила, що не тисне зверху, а стоїть під фундаментом сім’ї, тримаючи її, коли світ хитається.
Бути чоловіком – означає бути притулком. Для дружини, яка втомилася. Для дітей, які шукають захисту. Для самої оселі, в якій має панувати тепло, світло і тиша. Не завжди потрібно багато слів – часто достатньо бути поруч, міцно обійняти, мовчки вислухати, не осуджуючи.
Любити – це бачити в дружині Божий дар. У повсякденних речах, у зморшках під очима, у клопотах дня. Любити – це молитися за неї вночі, коли вона спить, і дякувати Господу, що саме її дав тобі на все життя. І навіть якщо часом не розумієш її слів чи вчинків – все одно люби. Не тому, що вона ідеальна, а тому, що твоя.
Справжній чоловік – не той, хто вимагає послуху, а той, хто заслуговує на нього любов’ю, лагідністю, вірністю. Бо головність, дарована Богом, – це не про владу, а про служіння. Не про трон, а про хрест. І лише той, хто з любов’ю несе цей хрест, може називатись главою родини.
**** [[https://www.facebook.com/100063702520939/posts/1444739877659416/?mibextid=rS40aB7S9Ucbxw6v][4]]
Є такі люди ніби від самого Бога послані, щоб нагадати нам, якою має бути справжня любов, тиха, лагідна, постійна. Вони не говорять про добро, вони просто ним дихають. Не вимагають вдячності, не очікують визнання, просто живуть і світять, як лампа в темній кімнаті, навіть тоді, коли ніхто не помічає цього світла.
Біля них серце відтаює, навіть якщо довго було холодним. Душа починає довіряти знову. У їхній присутності хочеться бути кращим, ніж ти є, чистішим, правдивішим. І коли життя розкидає нас по світу, такі люди залишаються в пам’яті назавжди, як запах хліба дитинства, як дотик руки матері, як спокій вечірньої молитви.
Якщо Господь подарував тобі таку душу поруч, бережи її. Це не просто людина, це жива присутність Божої любові у твоєму житті.
**** [[https://www.facebook.com/100063702520939/posts/1481877767278960/?mibextid=rS40aB7S9Ucbxw6v][5]]
Справжня зустріч починається там, де закінчується егоїзм. Поки ми шукаємо вигоду, увагу чи підтвердження власної значущості, ми дивимось, але не бачимо, торкаємось, але не відчуваємо. Лише тоді, коли серце перестає вимагати і починає дарувати, починає жити чудо справжнього зв’язку.
Любов, це не обмін, а подих душі. Вона не питає, чи отримає щось натомість. Вона просто є. І коли ти починаєш любити без очікувань, слухати без наміру відповісти, дивитись без оцінки, тоді перед тобою відкривається людина, така, якою її створив Бог.
Ми приходимо у світ не для того, щоб нас бачили, а щоб ми самі навчилися бачити інших. І коли це стається, тиша наповнюється смислом, слова стають непотрібними, бо дві душі вже говорять мовою любові.
Саме тоді і відбувається зустріч, не випадкова, не зовнішня, а глибока, вічна. Та, що залишає в серці тепло і спокій. Бо через неї торкається нас Сам Бог.
**** [[https://www.facebook.com/share/p/1733tcD8tX/?mibextid=rS40aB7S9Ucbxw6v][Любов — основа всього]]
Любов є тією невидимою силою, яка тримає небо і землю. Вона освітлює навіть найтемніші куточки серця, зцілює рани, що здавалися смертельними, і дарує нове життя там, де була пустеля. Коли серце наповнене любов’ю, тоді не страшні ні випробування, ні зради, ні темрява - все це відступає, бо де є любов, там є Бог.
Не забуваймо, що любов не в словах, а в ділах. Вона проявляється в простій усмішці до ближнього, у вмінні пробачати, у молитві за тих, хто нас зневажає, у тихій жертві, яку ніхто не бачить, окрім Господа. Саме така любов будує вічність.
Тому бережи її в серці, як найбільший скарб. Не дай образам і гордості її вкрасти, не дозволь байдужості її заглушити. Бо коли в людині є любов, вона стає схожою на дитину Божу, яка завжди радіє і вірить. І тоді все життя наповнюється сенсом, а душа спочиває у мирі.
**** [[https://www.facebook.com/share/p/19YQL4UEKc/][Найважче в цьому світі - змінити себе]]
Найважче в цьому світі - не змінити когось, а змінити себе. Стримати слово, коли хочеться крикнути. Простити, коли серце кричить від образи. Пригорнути, коли раніше б пішов. Помовчати, коли хочеться довести. І все це - не для вигоди, не для того, щоб бути кращим у чужих очах, а щоб зростати в любові. Бо де любов - там Бог. А де Бог - там світло, там доброта, там лагідність, там взаєморозуміння.
Людям має бути добре одне з одним - інакше навіщо ми разом? Не для того ж, щоб ранити, принижувати, змагатись і перемагати? Ми разом, щоб бути тими, хто лікує. Хто витирає сльози, підтримує руку, молиться поруч. Але це можливо тільки тоді, коли ми згодні працювати над собою. Не відразу ідеально, не одразу лагідно. Але щодня - трохи більше терпіння, трохи менше гордості, трохи більше світла.
І це - найвища праця. Але й найпрекрасніша. Бо саме в ній народжується справжнє щастя - коли двоє поруч не через те, що зручно, а через те, що полюбили, навчилися приймати і нести один одного в любові.
Боже, дай нам сили працювати над собою, щоб бути тими, з ким іншому добре
**** [[https://www.facebook.com/100063702520939/posts/1397902182343186/?mibextid=rS40aB7S9Ucbxw6v][Сім’я - це скарбниця]]
Діти не запам’ятають, скільки грошей ти приніс у дім, але вони завжди пам’ятатимуть, як ти обіймав їх перед сном, як тримав за руку в складну хвилину, як говорив слова, що підтримували й підіймали. Подружжя не цінує нові речі так, як відчуття, що його кохають і оберігають.
Сім’я - це скарбниця, де кожна хвилина уваги, кожне пробачення, кожна спільна молитва стають вічними цінностями. Це той єдиний рахунок, що ніколи не знеціниться, бо він збережений у небесному банку Божої пам’яті.
Тож не шкодуй часу на цей скарб. Вкладай у нього серце, і твої близькі завжди будуть багатими любов’ю, а ти сам - найщасливішим у світі.
**** [[https://www.facebook.com/share/p/16rwDaCTz4/][Щирість любові]]
Саме вдома перевіряється наша щирість, бо там нас знають справжніми - без масок, без прикрас, без зовнішньої побожності. Там не сховаєш роздратування за усмішкою, не прикриєш байдужість добрими словами. Милосердя вдома - це коли ми втомлені, але все одно обіймаємо; коли нас образили, але ми мовчки прощаємо; коли хочеться спокою, але ми йдемо мити посуд, бо хтось інший змучений ще більше.
Милосердя - це не лише дати хліб голодному, а й поділитися останнім шматком із близьким, не дорікаючи. Не лише приголубити сироту, а й не гримати на свою дитину вночі, коли вона втретє проситься на ручки. Не лише провідати хворого сусіда, а й з ніжністю розчесати волосся своїй матері, яка вже не має сил підвестись.
Милосердя - це коли твоя сім’я не боїться тебе, не соромиться своїх сліз перед тобою, коли в твоїй присутності стає тепло, як біля вогню. Це не красиві слова - це невидимий щоденний подвиг, який бачить тільки Бог.
Бо якщо ми не здатні бути добрими до тих, хто поруч із нами - то вся наша «доброта» для інших буде лише тінню, а не світлом. І найперше милосердя, як і любов, як і віра - має жити в нашій хаті, серед наших рідних. І якщо ми будемо справжніми в малому - Господь довірить нам і велике.
**** [[https://www.facebook.com/share/p/1atDsd5hsZ/?mibextid=rS40aB7S9Ucbxw6v][Христос — Істина і шлях]]
Людина може мати знання, але не мати істини. Може мати силу, але не мати влади над серцями. Може мати армію, але не мати вірності душ. Може здобути трон, але втратити царство вічності.
А Христос, не маючи нічого земного, володів усім небесним. Він торкався душі одним словом і вона зцілювалась. Він дивився в очі - і серце горіло любов’ю. Він ішов босими ногами по пилюці, а за Ним ішли натовпи, бо Його присутність була життям.
Його відкидали, бо Його істина занадто ясна, щоб у ній сховатися. Його слова різали гріх, як меч, і не залишали місця для самообману. Його любов була такою сильною, що ставала докором кожному, хто жив для себе. І саме тому Його й розіп’яли.
Але смерть не змогла втримати Того, Хто є Життя. І сьогодні Він стоїть біля дверей кожного серця і тихо стукає, щоб увійти. Тільки від нас залежить - відкрити Йому або залишитися в темряві. Бо з Ним - світло, без Нього - вічна ніч.
Христос був і є найправдивіший виклик людству. І кожен має дати відповідь на цей виклик - прийняти Його чи відкинути. І в цьому рішенні визначається вся наша вічність.
**** Без любові
 - СПРАВЕДЛИВІСТЬ без любові робить людину ЖОРСТОКОЮ
 - ВІДПОВІДАЛЬНІСТЬ без любові робить людину БЕЗЦЕРЕМОННОЮ
 - ПРАВДА без любові робить людину КРИТИКАНОМ
 - РОЗУМ без любові робить людину ХИТРОЮ
 - ПРИВІТНІСТЬ без любові робить людину ЛИЦЕМІРНОЮ
 - КОМПЕТЕНТНІСТЬ без любові робить людину НЕПОСТУПЛИВОЮ
 - ВЛАДА без любові робить людину ТИРАНОМ
 - ЧЕСТЬ без любові робить людину ЗАРОЗУМІЛОЮ
 - ОБОВ'ЯЗКОВІСТЬ без любові робить людину ДРАТІВЛИВОЮ
 - БАГАТСТВО без любові робить людину ЖАДІБНОЮ
 - ВІРА без любові робить людину ЕГОЇСТИЧНОЮ
Все робімо від Любові, для Любові і в Любові.
**** [[https://www.facebook.com/share/p/17EFKzdLx2/][Найбільший скарб у світі - ті, хто тебе любить]]
Чим старшим я стаю, тим більше переконуюсь, що всі інші речі - гроші, речі, статус - не варті й крихти порівняно з живим теплом тих, хто поруч. Бо коли все інше руйнується, залишається тільки любов. Вона і є тим фундаментом, який не зносить ні буря, ні час.
Можна загубити все, але якщо маєш людей, які тебе люблять і за тебе моляться - ти найбагатший. Саме вони вміють зібрати твоє серце по шматках, коли воно розбите, саме вони дарують сенс і радість там, де інакше панувала б пустка.
І тоді розумієш: найбільший скарб у світі - це не золото і не влада, а чисте, щире, справжнє серце людини, яке б’ється в унісон з твоїм.
**** [[https://www.facebook.com/share/p/1L8zTdmNgZ/?mibextid=rS40aB7S9Ucbxw6v][Любов не в сильних емоціях, а у добрих щоденних дрібницях]]
Любов проявляється у звичайних щоденних кроках: підняти телефон і запитати, як справи у мами, обійняти дитину перед сном, сказати дружині добре слово, навіть якщо ти втомлений. Це прості речі, які не вимагають великого натхнення, але саме вони будують міцні мости між серцями.
Любов не завжди відчувається як полум’я, вона частіше схожа на тихе світло лампадки, яке горить без перерви. І що важливо - воно світить не для себе, а для інших. У цьому світлі легше жити, легше йти шляхом, навіть коли темрява намагається оповити душу.
Тож не шукай любові в сильних емоціях, шукай її у вірності добрим справам, у щоденних дрібницях, що оживляють серце. Бо хто чинить добро, той і є носієм любові, навіть якщо не відчуває цього кожної миті.
**** [[https://www.facebook.com/share/p/1BRHQijKoZ/?mibextid=rS40aB7S9Ucbxw6v][Любов — найбільший скарб]]
Якщо в серці живе любов, тоді навіть у найбільш темні часи можна відчувати світло і радість. Любов робить багатим навіть того, хто не має нічого матеріального, і робить щасливим того, хто проходить крізь біль і втрати.
А якщо в душі бракує любові, тоді й найбільші багатства, і найяскравіші успіхи стають порожніми, бо нема чим наповнити серце.
Щастя - це не зовнішні обставини, а внутрішній дар. І той, хто має любов, завжди має справжнє життя, бо саме любов є диханням Бога в нас.
**** [[https://www.facebook.com/100063702520939/posts/1431501568983247/?mibextid=rS40aB7S9Ucbxw6v][Любов - це хрест, щоденний вибір серця]].
Любов - це не примха і не короткий спалах почуттів, а щоденний вибір серця. Це означає йти поруч і тоді, коли легко, і тоді, коли важко. Це означає не відвертатися, коли інший слабне, а підставити плече. Це означає бачити не лише красу, а й рани, не лише усмішку, а й сльози.
Любов вимагає терпіння, бо людина, яку ти любиш, не завжди буде такою, як ти мріяв. Вона буде втомлюватися, помилятися, зневірюватися. І тоді справжня любов не зламається, а покриє все розумінням і вірністю.
Це хрест, який несеш не зі смутком, а з радістю, бо поруч із тобою жива душа, яку Господь довірив тобі. Любов - це відповідь на Божий дар, бо саме через любов ми найбільше уподібнюємося Йому. І тому вона справді назавжди, на все життя і навіть далі - у вічність.
**** [[https://www.facebook.com/100063702520939/posts/1431213059012098/?mibextid=rS40aB7S9Ucbxw6v][Любов забереш у вічність]].
Ми часто біжимо, женемося за тим, що завтра втратить будь-який сенс, витрачаємо роки на те, щоб довести щось комусь, щоб збудувати образ успішності, який не зігріє нас у вирішальну хвилину. Ми тримаємося за речі, а вони - за нас ніколи. Усе це згорає, тоне, розпадається. І тільки те, що було вкладене у серця інших людей, залишається й далі жити після нас.
Любов, яку ти дав, підтримка, яку ти приніс, тепло, яке ти залишив у пам’яті своїх рідних - ось що піде з тобою до вічності. Бо це єдине, що справжнє. У Божих очах важать не дипломи й нагороди, а чистота серця, здатність прощати й любити.
Тому мудрий той, хто вже сьогодні сіє зерна доброти й ніжності у своєму домі, серед друзів, у своїй роботі. Мудрий той, хто сьогодні цінує людей більше за речі, хто не відкладає обіймів, доброго слова, молитви за ближнього на завтра. Бо завтра може й не бути.
Живіть так, щоб останні хвилини не були гірким прозрінням, а тихою радістю, що ви вже на землі доторкнулися до справжнього життя - до любові, яку подарував нам Христос.
**** [[https://www.facebook.com/share/p/16NBqm7pL2/][Бог очищає нас стражданнями]].
Лише пройшовши через біль, серце починає по-справжньому розуміти, що таке любов. Бо любов не народжується на м’яких подушках комфорту, вона визріває у стражданнях, очищається у випробуваннях, і стає світлою лише тоді, коли людина, знеможена скорботою, все ж каже: “Слава Тобі, Господи”.
Бог не зламує нас стражданнями, Він очищає. Як вогонь очищає золото, так і біль очищає душу від гордості, самолюбства, від усього, що заважає справжньому світлу оселитися в серці.
І коли людина вміє дякувати навіть у скорботі, коли вміє бачити промисел Божий там, де інші бачать лише біль, тоді в ній народжується та любов, яка вже не залежить ні від радості, ні від смутку. Вона просто є, як тиха присутність Бога в серці.
Бо лише через терпіння ми вчимося милосердю, через біль, співчуттю, а через втрату, вдячності. І тоді серце починає любити не за щось, а попри все.
**** [[https://www.facebook.com/share/p/19tiyN9feG/][Любов - це щоденний вибір, не ідеальність, а вірність]].
Любов - це не феєрверк, що спалахує й гасне, а вогонь, який тихо горить у глибині серця, зігріваючи обох навіть у холодні дні життя. Вона не потребує гучних слів, бо проявляється у мовчанні, у погляді, у дотику, у присутності.
Любов - це щоденний вибір. Коли хочеться образитися, а ти вибираєш зрозуміти. Коли легше відвернутися, а ти залишаєшся поруч. Це не ідеальність, а вірність, не порив, а глибина.
Любов не шукає вигоди, не зважує, хто більше віддав, не веде підрахунків. Вона просто є, як дихання, як молитва, як подих душі.
І якщо Бог є Любов, то кожен, хто любить по-справжньому, вже торкається вічності.
**** [[https://www.facebook.com/share/p/1CvHNe5zxM/?mibextid=rS40aB7S9Ucbxw6v][Дивитись на слабкості ближнього як у дзеркало власної недосконалості]].
Такою дорогоцінною є людська вірність. Вона рідкісна, як перлина, знайдена серед піску. І коли хтось залишається поруч не тому, що йому вигідно чи легко, а просто тому, що любить і не може інакше, - це відблиск Божої присутності в серці.
Люди слабкі, і ми самі не раз підводимо інших. Тому треба ставитися до ближніх не з осудом, а з милосердям. Коли замість образи ми обираємо розуміння, тоді в нас народжується справжня зрілість серця. Бо не велич у тому, щоб ніколи не бути зрадженим, а в тому, щоб, будучи зрадженим, не втратити здатність любити.
Якщо ми навчимося бачити у слабкості ближнього дзеркало власної недосконалості, то не будемо кидати каменем, а простягнемо руку. Бо кожна добра душа, що встояла попри зраду, розчарування і біль, - це вже перемога любові над холодом світу. І в цій перемозі є справжнє диво Божої благодаті.
**** [[https://www.facebook.com/100063702520939/posts/1469811028485634/?mibextid=rS40aB7S9Ucbxw6v][Метанойя]].
Коли ти сам намагаєшся тягнути свій хрест, опираючись, з останніх сил, - то це і справді нестерпно важко. Але коли ти довіряєш Йому, коли дозволяєш Христу йти поруч і нести цей тягар разом з тобою, тоді відбувається диво. Тоді ярмо стає любим, бо ти вже не сам. Тоді біль перетворюється на шлях очищення, і навіть страждання починає мати сенс.
Саме в цьому таємниця: Бог не полегшує шлях, але дає нове серце, яке здатне йти цим шляхом без нарікання. Він не зменшує бурю, а змінює тебе так, щоб ти міг пройти крізь неї з миром у серці.
Христос не прийшов зробити нас просто трохи кращими людьми, більш моральними, вихованими чи побожними. Він прийшов зробити нас новим творінням. І це не косметичний ремонт душі, а повне відродження зсередини, яке вимагає, щоб старе єство померло. Тому Він і каже: “Хто хоче йти за Мною, нехай відречеться себе”.
Але в цьому самозреченні і є справжня свобода. Бо лише тоді, коли ти вмираєш для себе, ти починаєш жити для Бога. І тоді, коли здається, що ти все втратив, виявляється, що ти отримав усе. Бо разом із Ним ти знаходиш мир, який не залежить від обставин, і любов, яку не може відібрати жоден світ.
Так Христос і перетворює найтяжче на найлегше - не тому, що прибирає труднощі, а тому, що дарує Себе. І коли в тобі живе Він, тоді навіть хрест стає благословенням.
**** [[https://www.facebook.com/share/p/1GB97nkcEK/?mibextid=rS40aB7S9Ucbxw6v][Коли любив — жив не даремно]].
Життя – це не назавжди, і ніхто не знає, коли настане та мить, коли серце зробить свій останній подих. Але якщо в ньому було хоч трохи Любові – тоді не страшно вмирати.
Ми часто женемось за тінями: за речами, славою, визнанням, силою. Ми намагаємось довести світові, що варті чогось, хоча вартість людської душі не в грошах і не в званні. Вона – у чистоті серця, у вмінні любити, прощати, допомагати, співчувати.
Усе, що ми колись купили, залишиться тут. Усе, що ми колись будували руками, зітреться пилом часу. Але те, що ми будували серцем, залишиться у вічності. Там, де вже не буде болю, зради, заздрості, ні грошей, ні кар’єр, а буде лише одне питання: чи вмів ти любити?
Коли душа покидає тіло, вона шукає не золото, не документи, не свідоцтва про досягнення. Вона шукає світло. А світло – це Бог. І тільки той, хто жив з Богом, хто хоч трішки навчився любити, знайде шлях додому.
Тому поки ти дихаєш, поки бачиш небо і чуєш спів птахів – дякуй. Пробачай. Люби. Молися. Говори добрі слова тим, кого любиш, поки вони можуть їх почути. Не відкладай обійми на потім, бо потім може не настати.
І коли настане той останній ранок – ти не злякаєшся. Бо знатимеш, що жив не даремно, що твоя любов не зникла, а лише перейшла у вічність. І там, на тому березі, тебе зустріне Той, Хто створив тебе з любові – і з любов’ю чекатиме твого повернення.
Живи серцем. Бо тільки серце живе вічно.
**** Любов + молитва == Божа присутність
Любов відкриває двері, які не піддаються жодним словам. Вона проникає туди, де закрито для розуму, і зцілює те, що не може вилікувати час.
А молитва - це дихання душі, тихе світло, яке веде навіть крізь найгустішу темряву. Коли любиш і молишся, то серце починає чути не тільки себе, а й інших. Воно стає теплим, м’яким, здатним розуміти, прощати і приймати.
Без любові серце мертвіє, без молитви воно холоне. Але коли обидві з’єднані - тоді людина стає живим храмом Божої присутності. І навіть якщо довкола темрява, у її душі горить вогонь, який не згасне ніколи.
**** Духовне зростання подібне до зерна, яке проростає повільно
Іноді здаватиметься, що все стоїть на місці, що молитви не чутно, що серце холодне й не здатне любити. Але саме в такі дні Господь діє найглибше. Він зрощує в тобі зерно віри, поки ти вірно, день за днем, йдеш Його дорогою, навіть тоді, коли не відчуваєш світла.
Ти будеш падати, сумніватися, знову вставати, просити пробачення і знову починати спочатку. І в цьому - суть духовного шляху. Бо Царство Боже не приходить блискавично, воно проростає тихо, як колос під землею, поки не настане час його дозрівання.
І коли одного дня ти озирнешся назад, то з подивом і вдячністю побачиш, що в тобі вже живе спокій, смирення, і тиха, зріла радість. І тоді зрозумієш: це Господь збудував у твоїй душі Свій дім.
**** Любов і розлука
[[https://www.facebook.com/share/p/1BFwjXEtU8/?mibextid=rS40aB7S9Ucbxw6v][1.]] Справжня любов не руйнує, вона не тримає силоміць, не перетворює на полон. Вона дозволяє іншому жити так, як він може, а собі, так, як потрібно, щоб не загинути душею.
Ми не втрачаємо людину, коли йдемо від неї. Ми лише перестаємо бути поруч там, де нас не чують. І тоді починається інший шлях, шлях внутрішнього миру, смирення й відновлення.
З часом приходить розуміння, що іноді розставання, це не кінець любові, а її найвища форма. Коли серце, не тримаючи зла, відпускає, благословляючи іншого на його дорогу. Бо любов, це не лише залишитися, а й уміти піти, зберігши світло всередині.
І тоді, крізь сльози, але з вірою, кажеш:
«Господи, дякую за цю людину. Дай їй щастя, дай мені сили не знецінити любов, яку Ти дав. І навчи мене прощати не лише її, а й себе».
[[https://www.facebook.com/share/p/17jBM9ZjdE/?mibextid=rS40aB7S9Ucbxw6v][2.]] Часто болить не тому, що ми очікували занадто багато, а тому, що любили щиро. Ми вкладали серце, довіряли, прощали, молились за тих, хто навіть не цінував. І ось одного дня приходить тиша - така, в якій уже немає образи, тільки втома й розуміння.
Ми перестаємо чекати взаємності, бо навчилися бачити Божий задум у всьому. Господь допускає ці розчарування не для того, щоб ми зневірились у людях, а щоб ми навчилися покладати надію лише на Нього.
З часом усвідомлюєш: справжня любов не вимагає відповіді. Вона просто є, як світло - гріє навіть тих, хто стоїть спиною. І коли в серці з’являється така любов, ти більше не злишся на тих, хто не зміг, не відповів, не зрозумів. Ти просто благословляєш їх і йдеш далі своєю дорогою, знаючи, що все, зроблене з любов’ю, не було марним.
**** [[https://www.facebook.com/100063702520939/posts/1473461891453881/?mibextid=rS40aB7S9Ucbxw6v][Любов до Бога і любов до ближнього йдуть в парі]].
Усе наше життя тримається на двох заповідях: любові до Бога і любові до ближнього. Ці дві заповіді - немов два крила, без яких душа не може злетіти до неба. Коли ми любимо лише Бога, але зневажаємо людину поруч, наша любов стає сухою, теоретичною, позбавленою живої сили. А коли любимо ближнього, але забуваємо про Бога, тоді ця любов втрачає святість і перетворюється лише на земну прихильність. Тільки разом вони дають істинне світло і теплоту серцю.
Любити ближнього - це значить бачити в ньому образ Божий, навіть тоді, коли цей образ затьмарений гріхом чи слабкістю. Це вміння дивитися глибше, ніж зовнішнє, бачити не лише провину, але й біль, не лише падіння, а й можливість піднятися. Господь не відвертається від нас, коли ми грішимо, а навпаки, простягає руку. І ми покликані чинити так само.
Кожен день життя - це можливість навчитися любові. Іноді Бог посилає нам складних людей не для того, щоб нас роздратувати, а щоб ми навчилися терпінню, милосердю, щоб у нашому серці прокинулося те, що зветься справжнім християнством. Бо християнство - це не лише хрестик на грудях чи слова молитви, це життя серця, яке вміє співчувати, прощати, жертвувати.
Любов до ближнього - це найвищий доказ любові до Бога. Бо як можемо любити Того, Кого не бачимо, якщо не любимо того, хто стоїть поруч із нами? Коли ми приймаємо, розуміємо, підтримуємо інших, тоді Христос Сам торкається нашого серця і наповнює його миром.
І тому, якщо хочеш знайти шлях до Бога - почни любити людей. Не за заслуги, не за доброту, а просто тому, що вони - Його діти. І тоді Господь Сам поселиться у твоєму серці, бо там, де любов, там і Бог.
*** ШЛЮБ
**** [[https://www.facebook.com/100063702520939/posts/1430053015794769/?mibextid=rS40aB7S9Ucbxw6v][Будь для дружини]]...
Дружина - це не наймана працівниця і не тягар для чоловіка, а дар Божий. І коли Господь з’єднує двох людей у шлюбі, то не для того, щоб вони вичавлювали один з одного вигоду, а щоб разом навчилися любові, терпінню й взаємній жертовності.
Чоловік має бути опорою, щоб жінка поруч з ним почувалася захищеною, спокійною і бажаною. А жінка, своєю ніжністю й мудрістю, стає для чоловіка джерелом миру, радості й натхнення.
І тільки так шлюб стає справжнім таїнством, коли двоє, не шукаючи користі для себе, віддають серце одне одному і разом йдуть дорогою спасіння, тримаючись за руку, з молитвою до Бога.
**** [[https://www.facebook.com/100063702520939/posts/1484533537013383/?mibextid=rS40aB7S9Ucbxw6v][Голова сім'ї]].
Справжній послух народжується не зі страху, а з любові.  І тільки той чоловік, який сам живе з Богом, який знає смирення і вміє страждати заради інших, заслуговує бути названим главою сім’ї.  *Бо глава - це не той, хто наказує, а той, хто бере на себе відповідальність, хто першим стоїть під ударом, хто не шукає свого, а шукає добра для всіх, кого йому довірив Господь*.
Коли чоловік дійсно любить, його любов стає покровом для дружини і дітей.  Вона не пригнічує, а зігріває.  Вона не диктує, а піднімає.  І тоді навіть у найважчі дні вдома панує мир, бо Христос живе в серці такого чоловіка.  Він не скаже дружині різкого слова, навіть коли болить і коли важко.  Він пригорне її, навіть якщо сам потребує підтримки.  Він навчиться мовчати тоді, коли слова можуть ранити, і говорити тоді, коли мовчання може образити.
І коли дружина бачить у своєму чоловікові не гордого начальника, а лагідного воїна Божої любові - вона сама відкриває йому серце і йде за ним із довірою.  Бо справжня влада чоловіка - у його серці, а не в силі руки чи гучності голосу.
І ось тоді, коли любов стає жертвою, коли турбота стає молитвою, а мовчання - терпінням, сім’я стає маленькою Церквою, у якій сам Христос живе і благословляє.
**** [[https://www.facebook.com/100063702520939/posts/1484691246997612/?mibextid=rS40aB7S9Ucbxw6v][Не винось проблеми з сім'ї]].
Сім’я, це святиня, і вона втрачає силу тоді, коли її межі стають відкритими для чужих очей і язиків. Те, що відбувається між чоловіком і жінкою, між батьками і дітьми, має залишатися під покровом любові, довіри й мовчання. Там, де є молитва і повага, Бог діє. А там, де починаються плітки й поради від сторонніх, приходить спокуса і розбрат.
Не шукай розуміння у світу, шукай його у своїй родині і в Бозі. Бо чужа порада, навіть із добрими намірами, може внести смуту в те, що Господь ще лікує. Лише той, хто живе у вашому домі, знає справжню вагу кожного слова і кожної сльози.
Сімейні радості, це перли, які не можна виставляти на показ. А сімейні болі, це хрест, який треба нести удвох, а не розділяти на плітки. Сім’я тримається не на словах, а на тиші, у якій звучить взаємне прощення, довіра і любов.
Тож бережи свій дім від сторонніх вітрів. Говори з Богом, не з людьми. Бо Він єдиний, хто здатен дати пораду без користі, втішити без осуду і зцілити те, що для інших здається безнадійним.
**** [[https://www.facebook.com/100063702520939/posts/1335349365265135/][Шлюб]]
Шлюб це простір, де вчаться не засуджувати, а слухати серцем.
Де щодня заново обирають любити, навіть коли важко.
Де замість звинувачень - молитва, замість гордості - смирення.
Шлюб – це шлях, на якому дві недосконалі душі вчаться бути разом з Богом.
Це мистецтво бачити у ближньому дар, а не лише виклик.
Це вірність не емоціям, а обітниці, яку дали одне одному перед Господом.
Шлюб – це коли два серця зростають разом у Христі,
і кожна спільна рана стає місцем, де зцілює Любов.
Бо коли у центрі стоїть Бог, тоді жодна буря не зруйнує той дім,
де мешкає прощення, терпіння і щира, жива турбота.

[[https://www.facebook.com/share/p/1FWy9Sr8LE/][Сім’я - це не тягар, а дар]]. Це простір, де людина вчиться виходити за межі власного “я”, бачити потреби іншого і відповідати на них любов’ю. Там народжується справжня зрілість, бо саме у сімейних стосунках серце відточується, як золото у вогні. Любити - це означає жертвувати собою заради ближнього, не завжди отримуючи миттєву віддачу, але знаходячи глибший сенс у служінні.
Щасливим робить не кількість грошей чи успіхів, а тепло дитячих рук, що обіймають тебе після важкого дня, погляд дружини чи чоловіка, який дарує сили йти далі, і впевненість, що є ті, хто завжди стоятиме поруч. Це і є справжнє багатство, яке не зникає з часом і не обесцінюється.
Тому вчімося любити. Бо коли серце наповнене любов’ю, сім’я стає не випробуванням, а джерелом радості, світлом, що веде до самого Бога.

[[https://www.facebook.com/share/p/14JHP6F3SJC/][Сім’я - це та святиня, де народжується справжня радість і спокій]]. Не в кар’єрі, не в грошах, не в званні, а саме у родинному колі людина відчуває, що вона потрібна, люблена, що її чекають. Там, де чути дитячий сміх, де пахне маминим хлібом, де поруч рука дружини, а на обличчях рідних - щирість, там і є справжнє щастя.
Бо сім’я - це школа любові. Вона вчить прощати, терпіти, дякувати й віддавати без залишку. І навіть коли життя приносить труднощі, сім’я стає тою твердою скелею, на якій можна вистояти.
Якщо в серці є любов, то дім стає маленьким небом на землі. Не потрібно нічого надзвичайного, щоб бути щасливим - достатньо бути поруч з тими, кого любиш, і кожного дня дякувати Богові за цей безцінний дар.
**** [[https://www.facebook.com/share/p/1LbaHpzvnB/?mibextid=rS40aB7S9Ucbxw6v][Чоловік в житті жінки]]
Чоловік у житті жінки - це не лише супутник її радості, а й дзеркало, в якому зростатиме дитина. Його слова, вчинки, навіть погляди непомітно стануть взірцем для маленького серця. Якщо в ньому є доброта, мудрість, віра і сила духу - саме цим наповниться й душа дитини.
Але якщо в його серці панує грубість, байдужість чи безвідповідальність, то й дитина зростатиме з тими ж ранами. Бо виховання - це не лише настанови, а передусім приклад життя.
Тож обираючи, варто дивитися глибше, ніж на зовнішню красу чи матеріальні можливості. Варто питати себе: чи зможе він разом зі мною молитися, любити, прощати і вести родину дорогою світла? Бо саме це визначить, яким буде серце нашої дитини.
**** [[https://www.facebook.com/100063702520939/posts/1465764305556973/?mibextid=rS40aB7S9Ucbxw6v][Чоловік — слуга в сім'ї]].
Саме від чоловіка, залежить, чи буде в домі тепло, навіть коли на вулиці холод.  Чи буде в серці жінки спокій, навіть коли довкола буря.  Чи зростатимуть діти в любові, навіть коли світ повен тривог.
Бути головою сім’ї – це не влада, а служіння.  Це коли ти встаєш раніше, щоб усі могли спати спокійно.  Це коли мовчиш, аби не поранити.  Це коли вибачаєш, навіть якщо боляче.  Це коли стоїш перед Богом і молишся не за себе, а за неї – за свою дружину, за дітей, за дім.
Справжній чоловік не боїться бути ніжним, не соромиться любові й не ховає доброти за суворістю.  Його сила не в тому, щоб примушувати, а в тому, щоб берегти.  І тоді навіть найслабша жінка поруч із ним розквітає, бо відчуває – вона під захистом, вона люблена, вона не одна.
І саме тоді Господь благословляє таку сім’ю, бо в ній панує любов, що походить від Нього.  А там, де є любов, – там є життя.
*** [[https://www.facebook.com/100069002737468/posts/1114803370829744/?mibextid=rS40aB7S9Ucbxw6v][Відношення до батьків]].
Шануючи батьків, ми вчимося шанувати самого Бога, Який дав нам життя через них. У серці, де є пошана і вдячність до тих, хто нас народив і виховав, легше зростає смирення, лагідність і слухняність Господній волі.
Але якщо ми дозволяємо собі зневагу до батьків чи старших, то не тільки ранимо їхні серця, а й руйнуємо власну душу. Людина, що відкинула батьків, рано чи пізно стає сиротою в духовному сенсі, бо той, хто не вміє цінувати рідне, не зможе щиро цінувати нікого і нічого. Такі серця черствіють і втрачають ласку Божу.
Шанування батьків не обмежується лише словами поваги. Воно перевіряється конкретними справами: допомогою, увагою, готовністю вислухати, підтримати, послужити навіть тоді, коли це вимагає жертви. Бо любов без діла – мертва. І скільки разів старенькі батьки чекають бодай одного дзвінка, одного доброго слова, одного візиту – і не отримують цього. Хіба не є це тяжким гріхом байдужості?
А ще треба пам’ятати: діти завжди переймають приклад своїх батьків. Якщо ми не шануємо своїх тата й маму, то й наші діти, дивлячись на це, чинитимуть так само з нами. Тому пошана до батьків – це ще й посів зерна майбутнього благословення у власній родині.
П’ята заповідь – це не лише закон, це ніжне нагадування Божої любові: цінуй тих, через кого ти прийшов у цей світ, і твоє життя буде довгим і добрим. І навіть коли батьки вже відійшли, пам’ятай їх у молитвах, бо і після смерті вони потребують нашої любові.
Ця заповідь – наче міст між небом і землею. Вона навчає нас глибокої вдячності і вірності, які ведуть людину до вічного життя. Хто виконує її, той будує дім свого серця на камені, і ніякі бурі світу не зруйнують йог
*** Мені не важко - він мій брат, вона моя сестра
Під час війни в Японії хлопчик ніс на спині вбитого молодшого братика, щоб таємно поховати його вдома. Дорога була важка, очі запалі від втоми і сліз, а земля під ногами горіла від страху. Один із солдатів, спостерігаючи це, порадив йому покинути вже мертвого, щоб легше йти далі. Хлопчик подивився на солдата і тихо відповів: Він не важкий. Він не є для мене тягарем. Це мій брат.
Солдат зрозумів. Він сів на землю і гірко заплакав, бо побачив у простому вчинку більше ніж подвиг - побачив любов. Образ цього хлопчика, що не залишив брата, став символом єдності і людяності. Він навчає, що доброта вимірюється не вигодою, а серцем, яке готове нести навіть те, що здається неможливим.
Нехай думка «Мені не важко - він мій брат, вона моя сестра» стане нашим девізом і керівним світлом у щоденному житті. Щоб не бути байдужим перед болем іншого, не відвертатися тоді, коли потрібно простягнути руку, і не рахувати тягарі ближніх як свої обмеження.
Якщо хтось упаде - я підніму його на руки і піду з ним далі. Якщо вона спіткнеться - я підтримаю її і проведу до світла. Якщо хтось втомиться - я віддам частину своїх сил, щоб він відпочив. Якщо ослабне - я стану йому опорою і плечем, на яке можна спертися. Якщо хтось помилиться - я буду тим, хто першим простить і допоможе розкаятись. Якщо світ покине його або залишить без допомоги - я не залишу, я носитиму його на своїх плечах, тому що він не тягар мені, адже він мій брат чи моя сестра.
Господи, дай серце, яке не зважає на ризики та втрати, але віддає себе в служінні іншим. Зміцни мої руки, щоб я міг піднімати упалих, очисти мій розум від самозакоханості, щоб я бачив образ Твій у кожній людині. Нехай любов наша буде більшою за страх, а милосердя - сильнішим за байдужість.
Не для хвилинної слави, а для того, щоб створювати маленькі острівці спасіння в цьому бурхливому світі.
*** Щастя та радість
**** [[https://www.facebook.com/100063702520939/posts/1432488878884516/?mibextid=rS40aB7S9Ucbxw6v][Чистий внутрішній світ]]
 Те, що є в людині, важливіше того, що є у людини. Бо внутрішній світ - це справжнє багатство, яке визначає і обличчя, і вчинки, і всю долю. Людина може мати дім, гроші, славу, але якщо в серці пустка, гординя чи злоба, то всі ці надбання обертаються на тягар і руїну.
 А той, у кого в душі є світло, доброта, віра і любов, навіть у бідності буде багатим, навіть серед випробувань буде щасливим. Бо серце, наповнене Богом, завжди сповнене миру, який ніхто не може відібрати.
 Тому найперше варто дбати про те, щоб мати чисту душу, совість без плями, серце відкрите для добра. Це скарб, який не знищить час і не відніме жодна сила світу. Бо саме те, що є в людині, вона й понесе з собою у вічність.
**** [[https://www.facebook.com/100063702520939/posts/1432127622253975/?mibextid=rS40aB7S9Ucbxw6v][Як жити в спокої та радості]]
 Коли людина перестає доводити, вона починає жити. Вона більше не витрачає сил на боротьбу з чужими думками, не шукає підтверджень власної цінності в очах інших. Її спокій народжується зсередини - із прийняття, вдячності й віри.
 Це не байдужість і не гордість. Це тиха впевненість, що твоє життя в Божих руках, і тобі не потрібно виправдовуватися за те, як ти відчуваєш, кого любиш, куди йдеш і ким стаєш.
 Справжня свобода починається там, де серце в мирі. Там, де замість доказів є добрі вчинки, замість слів - щирість, замість змагання - любов. І тоді щастя приходить непомітно, тихо, але назавжди.
**** [[https://www.facebook.com/100063702520939/posts/1432126168920787/?mibextid=rS40aB7S9Ucbxw6v][Щастя за будь-яких обставин]]
 Коли людина вчиться бачити добро навіть у дрібницях, її життя змінюється. Вона починає відчувати спокій, бо серце, наповнене вдячністю, не залишає місця для нарікань. Ми часто женемося за тим, чого нам бракує, і не помічаємо, що вже маємо все необхідне для щастя.
 Бог не обіцяє нам безхмарного життя, але дарує нам здатність радіти під час будь-якої погоди. І тоді навіть найзвичайніший день стає благословенням, якщо дивитися на нього з вдячністю.
 Коли ми перестаємо порівнювати своє життя з чужим, а починаємо дякувати за власне, серце наповнюється миром. І саме в цій тиші вдячності приходить справжнє розуміння: у більшості з нас усе добре, просто треба навчитися це побачити.
**** [[https://www.facebook.com/100063702520939/posts/1431196359013768/?mibextid=rS40aB7S9Ucbxw6v][Важко, але ти не сам]]
 Людина може бути знесилена, зневірена, але Боже дихання здатне підняти навіть із попелу.
 Нам треба лише не відштовхнути цю ніжність, не замкнутися в болю й образі, а відкритися і дозволити Богу торкнутися нас. Бо саме Його ласка робить з надломленого, відновлене, з пригаслого, полум’я, з пораненого, живе.
 І тоді ми вже не самі йдемо крізь темряву. Йдемо поруч із Тим, Хто сильний підняти і укріпити, Хто не дозволить зламатися остаточно, але в тиші і простоті поверне нам силу, мир і радість жити.
**** [[https://www.facebook.com/100063702520939/posts/1431210192345718/?mibextid=rS40aB7S9Ucbxw6v][Все потрібне для щастя вже нам дано]]
 Ми так часто женемося за примарними цілями, складаємо плани, мріємо про далекі вершини, а поруч проходить справжнє щастя - у посмішці дитини, у теплі рук коханої людини, у запаху свіжого хліба чи тиші вечірньої молитви.
 Людина ускладнює собі життя гонитвою за тим, що не є істинним. Вона будує палаци в уяві, замість того щоб з вдячністю глянути на маленьку хатинку власної душі, де може оселитися мир Божий.
 Щастя не в кількості речей і не в гучності овацій, воно в умінні зупинитися, видихнути, подякувати. Щастя - це коли серце живе з Богом, коли не мучать заздрощі й образи, коли світиться душа від простих і правдивих радощів.
 Тому, чим швидше ми навчимося помічати дрібниці і цінувати їх, тим швидше зрозуміємо, що все потрібне для щастя вже давно дано нам Небесним Отцем.
**** [[https://www.facebook.com/share/p/1DJGw1kARn/?mibextid=rS40aB7S9Ucbxw6v][Коли приходить щастя]].
Щастя не приходить тоді, коли ти прагнеш бути схожим на когось, а тоді, коли залишаєшся собою. Людина, яка йде своїм шляхом, навіть якщо він здається вузьким і важким, відчуває справжню свободу. Бо там, де ти сам з Богом, там завжди світло, навіть серед темряви.
Не шукай підтвердження свого життя в чужих словах чи оцінках. Сьогодні вони захоплюються, завтра засуджують - та істина не змінюється від цього. Твій скарб у серці, а не в чужих вустах.
Будь вірний своїм мріям, працюй над ними, бо Господь благословляє тих, хто не складає рук. І навіть якщо спотикаєшся - це не поразка, це крок вперед. Кожне падіння робить тебе мудрішим, а кожна перемога - ближчим до справжнього щастя.
І пам’ятай: щастя не у гучних оваціях і не у чужій заздрій усмішці, а у тиші твого серця, де живе любов і мир. Там, де ти щиро любиш, де молишся, де твориш - там і є твій рай.
*** [[https://www.facebook.com/share/p/1A3cFMFmzv/][Для чого ми потрібні Христові всі]]?
Христос не прийшов, щоб підфарбувати чи підлатати наше старе життя, а щоб подарувати зовсім інше - нове, чисте, вільне, справжнє. Йому потрібне не наше «трошки», не години на молитву, а потім повернення до себе, ні - Йому потрібні ми повністю, з усіма нашими ранами, слабкостями, навіть тими потаємними кутками серця, яких ми самі соромимось.
І тому Його заклик - і важкий, і легкий водночас. Важкий, бо це смерть для нашого «старого я», для наших звичок, гордощів, мрій, що побудовані не на Бозі. Але легкий, бо Він бере на Себе те, що ми самі ніколи б не подужали. Його ярмо любе, бо це ярмо любові, і Його тягар легкий, бо Його несемо вже не ми самі, а Він у нас і через нас.
Це найбільша таємниця християнського життя - і водночас найбільша надія. Христос не хоче зробити нас просто трохи кращими. Він хоче, щоб у нас народилось нове серце, нова воля, нова людина. Щоб ми вже жили не ми, а Христос у нас. І тільки тоді ми дійсно розуміємо, що означає свобода і що означає спокій, коли навіть хрест стає не тягарем, а благословенням.
*** [[https://www.facebook.com/share/p/1GnZkBwWKX/][Згубність бути дуже правильним]].
Велика трагедія: коли ми, що покликані бути світлом світу, самі перетворюємось на темряву. Коли замість живого Бога ми пропонуємо людям лише форму, замість істини - красиві слова, замість любові - холодну мораль. Ми забуваємо, що Христос прийшов не для того, щоб створити «релігію», а щоб дати Життя, і то з надлишком.
І тоді секулярний світ, який ми засуджуємо, виявляється чеснішим за нас. Бо він відверто кричить: «Нам бракує Бога!», а ми, прикрившись іконами й обрядами, робимо вигляд, що вже маємо все. Світ голодний по Любові, а ми годуємо його правилами. Світ сумує по Христу, а ми даємо йому тіні Христових одеж.
Найбільша небезпека - це самозаспокоєння. Тоді й молитва стає ідолом, і храм стає ідолом, і навіть віра стає ідолом, коли в них немає живого Духа. Бо Бог не в тому, щоб правильно скласти руки чи поставити свічку, а в тому, щоб серце було розп’яте для світу і відкрите для ближнього.
Тому сьогодні Церкві треба почати не з проповідей про світ, а з покаяння за власну глухоту. Бо поки ми самі не заплачемо над тим, що втратили Христа серед своїх «правильностей», доти ми не зможемо показати Його нікому іншому. І можливо тоді, в нашій убогості та розбитості, Господь знову відкриє Себе - як Тим, хто несе справжнє Життя. /Див. схоже у Дедюхіна/
*** [[https://www.facebook.com/share/p/17Wk4bLfak/?mibextid=rS40aB7S9Ucbxw6v][Як не заразитися злом]].
Людина, яка все життя воює з неправдою, може сама почати брехати, аби досягти мети. Той, хто гнівно викриває чужу жорстокість, іноді сам стає жорстоким у словах чи вчинках. Той, хто надмірно бореться з гріхом у ближньому, може й не помітити, як цей же гріх проростає у власному серці.
Святі отці застерігали нас від цього. Бо боротьба без смирення і молитви не очищає, а заражає. Якщо я дивлюся на зло з ненавистю, то потрохи воно входить у мене. Якщо я дивлюся на зло з молитвою до Бога, то світло Христове спалює його, не залишаючи сліду.
Тому завжди треба пам’ятати: не ми перемагаємо гріх, а Господь у нас. Наше завдання - не озлобитись, не стати схожим на те, проти чого ми повстали, а зберегти серце м’яким, чистим і люблячим. Бо тільки любов долає темряву. І тільки Христос перемагає диявола.
Хто дивиться на зло з ненавистю - стає його образом. Хто дивиться на зло з Христом у серці - той стає образом Божим. /Див. схоже у Дедюхіна/
*** [[https://www.facebook.com/100063702520939/posts/1449002893899781/?mibextid=rS40aB7S9Ucbxw6v][Подяка все, що маю]].
Схиляю голову перед Тобою, Боже, бо все, що маю, від Тебе. Я не заслуговую такої любові, але Ти її даруєш щоденно. Дякую Тобі за дім, за близьких, за хліб насущний, за кожен подих і кожну мить, у якій живе Твоя благодать.
Господи, я віддаю Тобі свій сон і свій ранок, свою працю і відпочинок, свої радощі й випробування. Веди мене дорогою світла, очищай серце від темряви і наповнюй його любов’ю.
Я хочу, щоб життя моє було піснею вдячності Тобі, щоб кожне слово, кожна дія і навіть тиша моя свідчили про Твою доброту. Дай мені сили ніколи не забути, що тільки Ти - моя надія, моя фортеця і мій мир. Амінь.
*** [[https://www.facebook.com/share/p/17YwoqMmEP/][Для чистого все чисте]].
Якщо в душі твоїй панує мир і любов, ти бачиш у людях добро, навіть коли вони помиляються. Якщо серце сповнене світлом, то й світ навколо здається світлішим. Але якщо в тобі живе осуд, гнів чи заздрість, то й у ближньому ти помічаєш лише їхні тіні, бо дивишся не очима любові, а очима власних ран.
Людина, яка навчилась прощати себе, здатна по-справжньому прощати інших. Той, хто прийняв власну слабкість, ніколи не зневажить чужу. І навпаки, хто не знайшов миру в собі, шукає ворогів у кожному.
Тому справжнє самопізнання не в тому, щоб досконало знати свої риси чи здібності, а в тому, щоб побачити в собі образ Божий і навчитися бачити Його в кожній людині. Бо коли душа пізнає Бога в собі, тоді в кожному обличчі вона бачить свого брата чи сестру, а не ворога. І саме тоді починається справжнє життя в любові.
*** [[https://www.facebook.com/100063702520939/posts/1454362583363812/?mibextid=rS40aB7S9Ucbxw6v][Довіра Богу]].
Коли ти довіряєш Богу, приходить тиха певність у серце. Ти перестаєш метушитися, перестаєш шукати винних чи відповідей, перестаєш виправдовуватися. Залишається лише спокійна тиша, як у храмі, коли світло від свічки м’яко лягає на ікони. У цій тиші серце починає дихати рівніше, сповнюється теплом і вірою, що все й справді буде добре.
Цей спокій не тому, що обставини змінилися, а тому що змінився ти. Ти поклав усе у руки Отця, Який бачить далі за тебе. І тоді навіть біль, навіть невідомість стають місцем зустрічі з Ним. І в ту мить, коли Господь розкриває твоїй душі, як дбайливо Він вів тебе крізь бурі, справді залишається лише сказати: «Господи, люблю і дякую Тобі!»
Це не просто слова, це як вдих світла після довгого мороку, як дотик вітру після задушливого дня. Це початок нового життя, у якому вже не так страшно й не так самотньо. Бо там, у глибині, ти знаєш: Він поруч.
*** [[https://www.facebook.com/share/p/1BCmcXvUSq/][Самопізнання, щоб побачити в собі образ Божий і навчитися бачити Його в кожній людині]].
Якщо в душі твоїй панує мир і любов, ти бачиш у людях добро, навіть коли вони помиляються. Якщо серце сповнене світлом, то й світ навколо здається світлішим. Але якщо в тобі живе осуд, гнів чи заздрість, то й у ближньому ти помічаєш лише їхні тіні, бо дивишся не очима любові, а очима власних ран.
Людина, яка навчилась прощати себе, здатна по-справжньому прощати інших. Той, хто прийняв власну слабкість, ніколи не зневажить чужу. І навпаки, хто не знайшов миру в собі, шукає ворогів у кожному.
Тому справжнє самопізнання не в тому, щоб досконало знати свої риси чи здібності, а в тому, щоб побачити в собі образ Божий і навчитися бачити Його в кожній людині. Бо коли душа пізнає Бога в собі, тоді в кожному обличчі вона бачить свого брата чи сестру, а не ворога. І саме тоді починається справжнє життя в любові.
*** [[https://www.facebook.com/share/p/1BdmPFfLyp/?mibextid=rS40aB7S9Ucbxw6v][Самодостатність у Христі]].
Це особливий шлях дорослішання душі, коли ти вже не шукаєш підтвердження власної цінності у чужих словах чи вчинках. Ти починаєш усвідомлювати, що твій мир і твоя радість залежать від Господа і від того, як ти сам відкриваєш Йому своє серце.
Людські очікування мінливі: сьогодні тебе схвалюють, завтра критикують, післязавтра забувають. Але Божа любов незмінна. І коли вчишся спиратися на неї, приходить дивовижна свобода. Ти вже не втрачаєш сил на те, щоб догоджати всім, а натомість прагнеш жити у правді, у світлі Божих заповідей.
І саме тоді відкривається справжня глибина стосунків з людьми: ти можеш дарувати любов без страху, служити без розрахунку, бути поруч щиро й по-справжньому. Бо твоя душа вже не залежить від чужих оцінок, а відчуває міцність у Христі, Який є твоїм миром і твоєю надією.
Це і є та гармонія, яку ми шукаємо - не зовнішня, а внутрішня, де серце стає спокійним навіть серед бур.
*** Ми ніколи не станемо досконалими.
**** [[https://www.facebook.com/share/p/1A1McJYCJT/][Бог приходить не до ідеальних]].
Бог не чекає від нас ідеальної поведінки, Він чекає справжнього серця. Серця, яке не боїться сказати: «Господи, я втомився… мені важко… я не розумію, але я вірю Тобі». Саме така відвертість розкриває двері, крізь які входить Божа благодать.
Ми часто думаємо, що повинні постати перед Ним досконалими, без гріхів, без сумнівів, без страхів. Але Бог приходить не до ідеальних, а до чесних. До тих, хто не ховає своє серце за правильними словами. Бо правда, це мова, якою говорить Господь.
Коли ми перестаємо грати ролі, тоді життя набуває глибини. Ми вже не намагаємось бути кращими, ніж є, а просто дозволяємо Богові творити в нас добро. І тоді Його світло пронизує навіть наші слабкості, перетворюючи їх на джерело сили.
Правда, це зустріч. Людина, яка живе в правді перед Богом, не боїться ні себе, ні інших. Вона не грає, не ховається, не бреше. І саме така людина стає вільною. Бо свобода, це не робити, що заманеться, а бути тим, ким тебе створив Бог.
Тож не бійся прийти до Нього зі своїм сумом, з розгубленістю, зі своїми поразками. Бо тільки той, хто став перед Богом у правді, може по-справжньому сказати: «Господь мій і Бог мій!», і почути у відповідь: «Мир тобі».
*** [[https://www.facebook.com/share/p/1CrQvfDvxS/][Мета Церкви]].
Важливо не зупинятися лише на зовнішньому. Церква покликана бути місцем зустрічі з Христом, а не кінцевою метою. Літургія, таїнства, молитви - це двері, через які ми маємо входити у спілкування з Богом, а не замикатися у формі без змісту.
Можна багато разів запалювати свічки, ставати на коліна, співати псалми, але якщо серце залишається холодним і закритим для Бога та людей, то все це перетворюється лише на релігійний театр. Христос не прийшов заснувати релігію для галочки - Він приніс Життя, яке змінює людину зсередини.
Справжнє християнство - це коли твоє серце стає храмом, коли Христос живе в тобі, а твоє життя стає проповіддю Його любові. Це означає бути світлом там, де темрява, підтримкою там, де біль, милосердям там, де байдужість.
Якщо ми маємо Христа в серці, тоді й Церква оживає для нас, бо вона є Його Тілом. Але без цього живого зв’язку все зводиться лише до традиції, що не рятує.
Тому головне питання, яке кожен має поставити собі: чи я лише в церкві, чи я дійсно у Христі?
*** [[https://www.facebook.com/100063702520939/posts/1472454481554622/?mibextid=rS40aB7S9Ucbxw6v][Навіщо йти до Церкви]].
Церква - це не місце, куди приходять просити допомоги час від часу, а живий організм, у якому людина зростає, очищається, змінюється. Увійшовши в неї серцем, людина починає жити не лише своїми силами, а силою Божою.
У Церкві Христос стає не просто об’єктом віри, а центром усього життя. Там душа, наче дитя, навчається знову довіряти, молитися, прощати, любити, терпіти. Там усе, що здавалось нерозв’язним, починає прояснюватися, бо в людині оживає благодать, яка є єдиним справжнім учителем і цілителем.
Коли ж людина стоїть осторонь, намагаючись знайти розраду без участі у Таїнствах, без покаяння, без спільної молитви, вона нагадує гілку, що відірвалася від дерева і шукає, як вижити. Але ж життя в гілці тільки тоді, коли вона живиться соком від кореня. Так само і в нас - усе оживає лише тоді, коли ми в Христі і в Його Церкві.
Увійдіть у це живе Тіло Христове не розумом, а серцем, не як гість, а як дитя, що повертається додому. І тоді все, що було болем, стане шляхом, усе, що було тягарем, перетвориться на благословення.
*** Літургія
Літургія, це не місце для досконалих, а простір, де Бог лікує недосконалих. Ми не йдемо туди, щоб показати свою святість, а щоб отримати силу для боротьби з власною неміччю. Господь не чекає від нас бездоганності, Він чекає присутності. Просто прийди. Стояти поруч з Христом важливіше, ніж відчувати щось велике.
Навіть якщо розум блукає, навіть якщо серце холодне, навіть якщо стоїш і здається, що нічого не розумієш, усе одно залишайся. Бо там, де звершується Таїнство, присутній Сам Бог, і навіть твоя мовчазна присутність є вже участю в Його благодаті.
Ми часто шукаємо духовних почуттів, хочемо, щоб нас зворушило, щоб щось відчулося, але справжня віра не в почуттях, а у вірності. Стояти перед Богом, навіть коли душа мовчить, це вже молитва. Це знак, що ти не здаєшся, що вірність тобі дорожча за емоції.
І з часом, непомітно, ця вірність почне тебе змінювати. Як одяг, який увібрав аромат пахощів, навіть якщо ти нічого не купував, так і душа, яка стоїть у Божій присутності, почне наповнюватися тихим світлом, миром, теплом.
Головне приходь. Навіть якщо стоїш, як колода, навіть якщо в серці темно, навіть якщо думаєш, що недостойний. Бо кожен крок до храму, це крок до Отця, Який чекає. І одного дня ти відчуєш, що вже не просто стоїш, ти живеш Літургією, дихаєш нею, і тоді вже не ти приходиш до Бога, а Бог живе в тобі.

**** [[https://www.facebook.com/share/p/17Gkpnz9t8/][Любити ворогів Лк.6, Мт.5, Нагорна Проповідь]].
Коли ми починаємо сприймати життя у світлі Божого Промислу, то серце поступово наповнюється миром. Ми вже не спішимо ображатися чи відповідати злом на зло, бо розуміємо, що кожна зустріч є Божим уроком для нашої душі. Навіть найгіркіші образи і несправедливості можуть стати благословенням, якщо ми побачимо в них нагоду для смирення, терпіння і молитви.
Не людина мене випробовує, а Господь через неї дивиться, як я відреагую: чи збережу мир у серці, чи піддамся пристрастям. І якщо я зриваюся - то не ворог винен, а моє серце, яке ще не навчилося жити в любові.
Тому Господь і сказав: «Любіть ворогів ваших, благословляйте тих, що проклинають вас, творіть добро тим, що ненавидять вас і моліться за тих, що кривдять вас і гонять вас» (Мт. 5:44). У цих словах захована справжня свобода. Бо хто молиться за ворога, той вже не раб образи, не раб гніву, а дитина Божа, яка черпає силу від Отця Небесного.
І тоді ворог перестає бути ворогом, а стає моїм благодійником, через якого я відкриваю свою слабкість і водночас знаходжу дорогу до очищення. Це і є таємниця християнського життя - бачити в усьому руку Божу і навіть у скорботах знаходити зерно спасіння.
**** [[https://www.facebook.com/100063702520939/posts/1443457081121029/?mibextid=rS40aB7S9Ucbxw6v][Як благословити за захистити дитину]].
Як благословити дитину
Немає нічого сильнішого і чистіше на світлі, ніж материнська любов. Не важливо, 5 або 40 років дитині, благословити її ніколи не пізно. Це буде служити надійним оберегом у всіх складних ситуаціях. Якщо у тебе важка дитина, благослови її, якщо часто хворіє - теж. Навіть якщо все у неї добре і вона щаслива, благослови її, щоб нічия заздрість не лякала.
Хтось піде в школу, хтось в інститут, хтось в армію, хтось одружиться ... Так що не пожалій кілька хвилин свого часу на благословення дитини перед важливим кроком в життя. Як це працює і як це правильно зробити
💥  БЛАГОСЛОВЕННЯ   МАТЕРІ
Перша згадка про благословення можна знайти в Старому Завіті Біблії. Його дав Бог Адаму і Єві, коли поставив управляти раєм і наповнювати землю. Енергетично, дитина - продовження матері і на кожного з нас мама має величезний вплив, і ми пов'язані з нею невидимими нитками. Саме тому вона може прямо впливати на долю своєї кровинки.
Благословляючи, мати створює навколо дитини якийсь захисний кокон, який не дозволяє їй потрапляти в неприємності і направляє всі дії в потрібне русло. Вважається, що людина, яку благословила мати, стає невразливою. Відмовляти в благословенні не можна, навіть якщо справи, на які потрібно давати благословення, батькам не подобаються, інакше дитини можуть підстерігати невдачі, що загрожують життю і здоров'ю.
При благословенні на важливі справи мамі треба прочитати молитву, а потім сказати побажання. Позитивний ефект буде простежуватися вже на сьомий день.
 🙏✨ МОЛИТВА БЛАГОСЛОВЕННЯ МАТЕРІ
“Господи Ісусе Христе, Сину Божий, молитвами Пречистої Твоєї Матері вислухай мене, грішну і недостойну рабу Твою. Господи, в ласці Своїй тримай чадо моє, помилуй і спаси його імені Твого ради. Господи, прости йому всі провини, вільні і невільні, скоєні ним перед Тобою.
🙏✨   Молитва “Благословення матері” – молитва семи днів, щоб діти були здорові та щасливі
Господи Ісусе Христе, Сину Божий, молитвами Пречистої Твоєї Матері вислухай мене. Господи, в ласці Своїй чадо моє, помилуй і спаси його імені Твого ради.
Господи, прости йому всі провини, вольнi і невольнi, вчинені ним перед Тобою. Господи, настав його на істинний шлях заповідей Твоїх і подай йому і просвіти світлом Твоїм Христовим, на спасіння душі і зцілення тiла.
Господи, благослови його в будинку, біля будинку, в школі, в полі, в роботі і в дорозі, і на кожному місці Твого володіння. Господи, збережи його під покровом Твоїм Святим.
Господи, захисти його від видимих ​​і невидимих ​​ворогів, від усяких бiд, зол і нещасть. Господи, зціли його від будь-яких хвoроб, очисти від усякої cквeрни і полегшu його душевні cтpaждання і скoрботи.
Господи, даруй йому благодать Духа Твого Святого на многії літа життя, здоров’я і здорового розуму.
Господи, додай і зміцни його розумові здібності і тiлесні сили. Господи, дай йому Твоє благословення на блaгочeстиве сімейне життя і благочестиве дітонародження.
Господи, даруй і мені, батьківське благословення на чадо моє в даний час ранку, дня, вечора і ночі імені Твого ради, бо Царство Твоє, всесильне і всемогутнє.
Амінь.
**** [[https://www.facebook.com/groups/483201180327002/permalink/1097988662181581/?mibextid=rS40aB7S9Ucbxw6v][Благословіння з Біблії]].
Нехай поблагословить тебе Господь і нехай Він тебе охороняє!
Нехай Господь засяє Своїм обличчям до тебе і помилує тебе!
Нехай Господь поверне Своє обличчя на тебе і хай дасть тобі мир!
‭‭Числа 6‬:‭24‬-‭26‬
**** [[https://www.facebook.com/share/p/14PLqC2fPBM/][Сила подяки]].
У подяці є сила, що перетворює скорботу на мир, а смуток – на розраду. Бо коли людина дякує навіть у важкі хвилини, вона визнає, що все – з Божих рук, і нічого не трапляється без Його любові.
Скажеш «Слава Богу за все» – і в душі розвидниться. Навіть якщо зовні нічого не змінилося, всередині вже народжується тиша, довіра, прийняття. Це коротке слово стає мостом між твоїм серцем і небом.
Дякуючи, ти наче кажеш Богові: «Я Тобі вірю. Я знаю, що все, що маю – для мого спасіння». І тоді Господь ніжно торкається душі, наповнюючи її спокоєм, який не дає цей світ.
Повторюй це просто, щиро, щодня: «Слава Богу за все». І побачиш, як зміниться твій погляд, твоє серце, твоє життя.
**** [[https://www.facebook.com/share/p/17KG9iij3Y/?mibextid=rS40aB7S9Ucbxw6v][Вбивство байдужістю і як лікуватись]].
Бійся байдужих - бо я зрозумів, що їхня тиха зрада набагато небезпечніша за гострий удар. Я бачив, як у мовчанні вмирає правда, як у байдужості згасає любов.
Я молюся, щоб Господь дав мені сміливість говорити правду лагідно, але наполегливо. Я вчуся бути тим, хто піднімає голос за того, хто потопає - не для слави, а щоб бути рукою Христовою тут, на землі. Коли я дію, навіть невеличким добрим вчинком, я відганяю байдужість, я даю іншим можливість знову любити.
І ще я боюся не того, що скажуть люди, а того, що я сам одного дня звикну до зла, прикриватиму його своїм мовчанням і стану співучасником. Тому я вибираю любов - не романтичну, не легку, а ту любов, що хрест несе, ту любов, яка прощає, але не потурає злу.
Молюся, щоб Бог навчав мене бачити людину за ворожою маскою і молитися за ворога так само, як молюся за друга. Бо тільки любов, освячена молитвою, перемагає зраду і вбивство байдужістю - і ця перемога починається в моєму серці.
**** [[https://www.facebook.com/share/p/16jjna4vzV/?mibextid=rS40aB7S9Ucbxw6v][Вдячність]].
Вдячність - це не просто слова, це стан серця, в якому живе Бог. Коли дякуєш, навіть за найменше, душа починає світитися зсередини. Вдячна людина ніколи не буває бідною, бо вона бачить щедрість там, де інші бачать нестачу.
Іноді достатньо одного “дякую”, щирого, без фальші - і серце іншої людини розквітає, немов весняна квітка після дощу. А іноді варто просто подивитися на небо й прошепотіти: “Дякую Тобі, Господи, що я живу, що бачу, що можу любити”.
Вдячність відкриває двері для нових благословень. Невдячність - навпаки, закриває навіть те, що вже було дано. Тому варто пам’ятати: кожен день, кожна людина, кожен ковток повітря - це дар. І коли починаєш це усвідомлювати, життя перестає бути боротьбою і стає молитвою.
**** [[https://www.facebook.com/share/p/17PoHnSeUT/][Ми хочемо гри лише на власну користь]].
Головна трагедія людства, небажання брати на себе відповідальність. Ми хочемо, щоб Бог керував світом за нашими правилами, але при цьому не хочемо, щоб Його воля керувала нами. Ми прагнемо справедливості, але часто лише тоді, коли вона має торкнутися інших, не нас самих.
Людина звинувачує Бога, бо так легше, ніж поглянути у власне серце. Легше сказати: “Ти допустив” ніж визнати: “Я згрішив, я оступився, я не чув Тебе”. Ми хочемо, щоб Господь був відповідальним за нас, але не хочемо бути відповідальними перед Ним.
І саме тому з кожним поколінням світ все далі від раю. Бо рай починається не на небі, а в серці, яке вміє сказати: “Господи, прости мене, бо я винен”. У цьому перший крок до зцілення, до спасіння, до миру з Богом.
Поки людина шукає винних, вона залишається у темряві. Але щойно вона визнає свою провину і звернеться до Бога зі щирим покаянням, світло повертається. Бо Бог не чекає пояснень, Він чекає серця, яке нарешті перестане виправдовувати себе і скаже: “Так, Господи, це я. Навчи мене жити інакше”.
** Інші
*** [[https://www.facebook.com/share/p/1Dt6HDkuaP/][БІБЛІЯ - МОБІЛЬНИЙ ТЕЛЕФОН]].
Уявіть, якби ми використовували нашу Біблію так само, як свій мобільний телефон. 
І що ми завжди носимо Біблію в сумках. І відкриваємо її у кожну вільну мить дня. І повертаємось шукати її, якщо забудемо її вдома чи в транспорті. І що ми надсилаємо повідомлення з її змістом. І ставимось до неї так, ніби ми без неї не можемо. І даємо її  молоді. І використовуємо її під час подорожі. І в  надзвичайних ситуаціях?
На відміну від мобільного телефону, Біблія не має обмеженої площі, вона "працює" скрізь.
Шукайте Господа, поки можна знайти Його; кличте Його, поки Він близько! ” (З 55.6)
У БІБЛІЇ ЗНАХОДИМО НОМЕРИ ТЕЛЕФОНІВ ДЛЯ ВСИХ НАДЗВИЧАЙНИХ СИТУАЦІЙ:
Коли вам сумно, відкривайте Євангеліє від Івана 14.
Коли хтось говорить погано про тебе, відкрий псалом 27.
Коли нервуєш, читай псалом 51.
Коли ви хвилюєтесь, відкривайте Євангеліє від Матвія 6,19.34.
Коли в небезпеці, читайте псалом 91.
Коли Бог здається далеким, шукайте псалом 63.
Коли хочеш відродити свою віру, відкрий послання до Євреїв 11.
Коли ти один, читай псалом 23.
Коли ти знервований, відкрий 1 послання  до Коринтян. 
Коли вам самотньо і сумно, читайте послання до Римлян 8:,31-39.
Коли хочеш миру та відпочинку, відкрий Матвія 11:25-30.
Коли ваш світ здається більшим за Бога, читайте псалом 90.
*** ВТРАТИ
 - Ірєромонах Арсеній Ревтов
Втрату не можна уникнути, але можна навчитися жити з нею.
Втрати — частина життя. Вони приходять непрохані і змушують нас відчувати біль, смуток, розгубленість. Але в кожній втраті є урок: вона вчить нас цінувати те, що ми мали, і відкривати серце для нових переживань.
Жити з втратою — не означає забути. Це означає прийняти біль, відчути його, дозволити собі сумувати, а потім знайти сили рухатися далі. Кожна втрата робить нас сильнішими, мудрішими і більш співчутливими до інших.
Не бійся відчувати, не бійся сумувати. Бо саме через це серце навчається любити глибше і жити повніше.
 - Ігумен Саватій ( Собко )
Я багато разів бачив, як Господь міняв хід подій, зупиняв те, що могло зруйнувати, і відкривав те, що здавалось неможливим. І кожного разу я розумів одне: не треба рватися туди, куди Бог не веде, і не варто боятися того, куди Він кличе. Бо Його воля завжди веде до миру, навіть якщо спочатку це шлях через бурю.
Коли ти довіряєш Богові, приходить тиха впевненість у серці. Ти перестаєш бігти за тим, що не твоє, і починаєш бачити, як кожен день має свій сенс, навіть коли здається, що нічого не рухається.
Світ може хитатись, плани можуть руйнуватись, але якщо Господь сказав “так”, ніхто не скаже “ні”. І якщо Він промовив “ні”, жодна сила не зробить “так”. Тому живи з миром у серці, бо все, що твоє, тебе знайде, а що не твоє, обійде стороною. І в тому теж буде благословення.
 - Олександр Олександрович Гаврилюк
Коли людина стикається з горем,  особливо від втрати близької людини, 
будь-які "поради" чи "кроки до покращення" можуть звучати порожньо або навіть ранить. 
Людина в такому стані не потребує інструкцій — вона потребує простору для свого болю і того, 
щоб цей біль був визнаний.
Що означає «бути» при втраті?
1. Прийняти право на почуття
Коли ми «просто є», 
ми дозволяємо собі відчувати те, що ми відчуваємо: 
біль, сум, злість, розчарування, безнадійність. 
Немає «правильного» способу горювати.

*** Доброта з точки зору науки.
Вот что писал писатель В.В.Варжапетян - Эфроимсон Владимир Павлович (1908–1989) – генетик.
В 1971-м (мне было 30 лет) я прочитал в «Новом мире» (№ 10, 1971) статью «Родословная альтруизма. Этика с точки зрения эволюционной генетики», которая потрясла меня до основания. Оказывается, альтруизм имеет прочные биологические основы, заложенные в ходе естественного отбора. То есть (это я уже потом для себя вывел) человек изначально добр, иначе как вид он не выжил бы, вымер бы много раньше, как питекантропы, неандертальцы и т.д.

*** [[https://www.facebook.com/share/p/1AcqLRhC3G/?mibextid=rS40aB7S9Ucbxw6v][⁹ Бо коли ти устами своїми визнаватимеш Ісуса за Господа, і будеш вірувати в своїм серці, що Бог воскресив Його з мертвих, то спасешся,До Римлян 10:9]]
© Біблія Онлайн, 2003-2025.
Ісусе Христе, я визнаю Тебе Господом і Спасителем свого життя.
Я вірю, що Ти страждав за мене, помер на хресті, був похований і славно воскрес із мертвих на третій день.
Ти переміг смерть і гріх.
Я визнаю усі свої гріхи перед Тобою і приймаю Твоє прощення, звільнення та вічне життя у Твоїх обіймах.
Дякую Тобі, Ісусе, що Твоя Свята Кров омила мене, очистила і зробила мене новим творінням у Тобі.
Я більше не раб гріха, я – дитина Божа, відкуплена дорогоцінною Кров’ю Ісуса Христа.
Господи, дякую Тобі за Твою безумовну любов, милість і щедру благодать.
Дякую за Духа Святого – мого Утішителя, Наставника і Силу, що веде мене у Істині.
Я належу Тобі, Ісусе.
Ти – мій Цар, мій Пастир, мій Спаситель, мій Захист, мій Вірний і Добрий Бог.
Ти – Господь усього мого життя!
Нехай Твоя слава сяє в мені, нехай Твоя воля звершується через мене.
Я поклоняюся Тобі, Ісусе, звеличую Твоє Святе Ім’я і довіряю Тобі в усьому. 
Слава Тобі навіки!
Амінь.

*** [[https://www.facebook.com/100064371654885/posts/1271714544984255/?mibextid=rS40aB7S9Ucbxw6v][Вчинок Закхея]].
 Щоби зрозуміти сенс учинку Закхея, погляньмо, що він отримав завдяки своїй наполегливості й рішучості. По-перше, не тільки побачив уславленого Вчителя, але й прийняв Його в гостину. По-друге, особиста зустріч з Ісусом радикально перемінила його життя. По-третє, ми навіть через дві тисячі років згадуємо цього митаря і знаємо, що він учинив. Із цієї перспективи зрозуміло, що докладені зусилля себе виправдали. 
 Сьогодні нам, може, і не треба лазити по деревах буквально; але точно доведеться потрудитися, щоб «побачити» Ісуса. Почати варто від простого запитання: а як ти «шукаєш» Ісуса? Скільки часу витрачаєш на перебування з Ним? Як часто вдивляєшся в ікону Спасителя або слухаєш Його слово?
*** Давайте...
 [[https://www.facebook.com/share/p/1A2gmqkbZe/][Давайте, і дасться вам]]: мірою доброю, натоптаною, утрушеною, переповненою віддадуть вам, бо якою мірою міряєте, такою ж відміряється і вам. (Євангеліє від Луки, 6:38)
*** Християнське слово НІ
 Чарівне слово "ні"
 До речі, це дуже християнське слово. Є така брехня - "християни ніколи нікому не відмовляють". Кістьми ляжуть, але всіх спасуть. А насправді так не працює. Не ми спасаємо, а Бог.
 Бо коли я вважаю, що можу і маю когось рятувати, то щось пішло не так. Ми не рятуємо, ми можемо допомогти, якщо інші потребують допомоги.
 Але я не про це. Я про слово "ні". Я кажу ні, коли люди просять зробити за них те, що вони можуть самі. Але не хочуть.
 Я кажу "ні", коли не маю сили допомогти. Бо з порожньої кишені нема що дати.
 Я кажу "ні", коли хтось хоче допомогти мені, а я не просила. Хоч навіть хочуть мені кращого.
 Але "ні", бо звідки їм знати, що для мене краще?
 Я кажу "ні" навіть на добрі речі, коли їх забагато. Бо все потрібно в міру.
 Я кажу "ні", коли людина переступає межі і хоче увійти в моє життя з брудним взуттям. А я таких не впускаю.
 Я кажу "ні" на багато речей, порад і пропозицій. Бо відчуваю, коли мені чогось забагато.
 І це нормально. Бо кожне "ні" чомусь одному - це "так" собі. Своєму серцю. Своєму здоров'ю. Своєму відпочинку, без якого навіть коні здихають. 
 А я не кінь. Ні)
 Навіть Бог не переступає межі людини і приймає кожне "ні". Хоч Йому я ніколи свідомо не відмовляю. Перед Його пропозиціями неможливо встояти
 Чарівне слово - не "будь ласка".  Чарівне слово - "ні".
 Як його сказати вголос і не вмерти від почуття провини?
 Спитай себе: а чи це добре для мене?
 Якщо ні - то "ні" і крапка.
*** Менше концентруйся на собі, а більше на Богові.
Гріх зневіри походить від надмірної зайнятості собою, своїми переживаннями, невдачами, і як результат - згасання любові до оточуючих, байдужість до чужих страждань, невміння радіти чужим радостям, народжується заздрість.
 Основа і корінь нашого духовного життя і сили - любов до Христа, і її потрібно в собі ростити і виховувати, вдивлятися в Його образ, проясняти і поглиблювати його в собі, жити думкою про Нього, а не про свої дрібні метушні успіхи і невдачі, віддавати  Йому своє серце - це життя християнина.
І тоді в нашому серці запанує тиша і мир, про що говорить св. Ісаак Сирін : «Примирися з собою, і примиряться з тобою небо та земля».
*** [[https://www.facebook.com/100064371654885/posts/1276627734492936/?mibextid=rS40aB7S9Ucbxw6v][Вдова, дві лепти, довіра Богові]].
Те, скільки я залишаю собі, свідчить про мою довіру Богові. Вдова з сьогоднішньої Євангелії не повинна була вкидати останнє, але саме це Ісус похвалив. Саме така «сліпа» чи, швидше, повна довіра подобається Богові.
Це можна перенести і на сили, які я «приберігаю», щоб мене ніхто зайве не обтяжив. На ставлення до своїх щоденних обов’язків: навіщо віддаватися повністю, якщо все одно ніхто не побачить? — Побачить. І примножить свої благодаті за довіру й вірність.
* Служби
** Велика Панахида
1) [[https://www.youtube.com/watch?v=erWbd3fScL8][Епіфаній]]
2) [[https://www.facebook.com/100007909020503/videos/1227705292691337/][Геннадій Коваленко]]

** Антипасха
https://www.youtube.com/watch?v=0HKkuvtGo-U
https://www.youtube.com/watch?v=aADNC1zF094
https://www.facebook.com/share/v/1ATfxQZDj2/
https://www.youtube.com/watch?v=xMAbKesEeek

** поминки
https://www.youtube.com/watch?v=vZLLR6_DAbY

** Причастя
[[https://www.facebook.com/share/p/17ccj2Ctt9/][Причастя на дому та в лікарні]]
 
* Шлюб та відносини (не клір)
** Дмитро Остапенко
[[https://www.facebook.com/reel/1866610387610407/?mibextid=rS40aB7S9Ucbxw6v][Вагомі підстави для розлучення]].
[[https://www.facebook.com/reel/4344452479213067/?mibextid=rS40aB7S9Ucbxw6v][Головні помилки чоловіків у стосунках]].
[[https://www.facebook.com/reel/1154704806118752/?mibextid=rS40aB7S9Ucbxw6v][3 речі, які вбивають чоловічу гідність у парі]].
[[https://www.facebook.com/share/v/1CaSqAnBah/][Чому багато людей не щасливі разом]]? Книги про шлюб та сім'ю. Служити іншому.
[[https://www.facebook.com/reel/821627957115173][Як жінці правильно реагувати на брехню чоловіка]].
[[https://www.facebook.com/OstapenkoDmitriy/videos/1012242540631146/?mibextid=rS40aB7S9Ucbxw6v][Головне паливо жінки у стосунках]]. Чого не вистачає жинці і чоловіку. Планування часу для сім'ї. Робота не розіб'ється, якщо буде невдача, а сім'я — розіб'ється.
[[https://www.facebook.com/reel/24417331044564120/?mibextid=rS40aB7S9Ucbxw6v][Чому навіть віруючі пари розлучаються]]? Бо потрібно будувати систему і у шлюбі, і у фінансах.
[[відновлювати внутрішній ресурс][Як відновлювати внутрішній ресурс]].

** Олександр Гаврилюк
*** [[https://www.facebook.com/share/p/199N2Nxu1Z/][Людина в горі]]
*** [[https://www.facebook.com/share/p/1AoAsR8pN8/][Господь виховує нас через досвід]].
Він дозволяє нам скуштувати те, що переживають інші, щоб ми не були черствими і байдужими. Щоб ми ставали людьми, здатними співчувати і розділяти тягар ближнього. Бо справжня любов полягає не у правильних словах, а в тому, щоб бути поруч, коли інший падає, і піднімати його молитвою, присутністю, добрим словом.
І тоді вже наші серця, які пройшли через вогонь скорбот, стають теплими і лагідними. Ми починаємо розуміти, що у світі немає чужого горя, немає чужого болю. Бо Христос Сам показав нам приклад - Він взяв на Себе біль усього світу, щоб ми могли навчитися любити по-справжньому.
*** [[https://www.facebook.com/oleksandr.gavriluk.934294/videos/1167405161919241/?mibextid=rS40aB7S9Ucbxw6v][Любов - це дар]]
Любов - це не наказ, а дар. Її не можна вимагати, її можна лише віддати від серця, щоб вона народила у відповідь любов і довіру. Якщо чоловік любить щиро, самовіддано, як Христос полюбив Церкву, то жінка природно відкриває серце для пошани і ніжності.
У родині не повинно бути диктату чи змагання за владу. Бо де починається боротьба, там вмирає ніжність. Справжня християнська сім’я стоїть не на рівності за правилами, а на гармонії сердець, де один бере на себе більше, аби другому було легше.
Дружина не перестає бути особистістю, а чоловік - головою сім’ї. Але ця голова повинна керувати не силою, а мудрістю і любов’ю. І тоді навіть у найтяжчих випробуваннях подружжя стоятиме разом, бо в центрі їхнього союзу буде не егоїзм, а Христос.
Хто навчився любити і жертвувати собою - той знайшов ключ до щастя в шлюбі. І тоді слова з Євангелія не тиснуть як закон, а звучать як пісня, бо вони оживають у серці.

*** [[https://www.facebook.com/100057215715956/posts/1323290172921494/?mibextid=rS40aB7S9Ucbxw6v][Переживання, що ведуть до онкології]].
"Переживання такого роду ведуть до онкології -  
багато переживань вдаряють по тілу, зменшують життя".
"Якось я познайомився на Кріті з жінкою, вона справила на мене величезне враження. Її думки були одна подяка і світло. Її залишив чоловік, хоча вона була дуже гарна. Але чоловік цього не оцінив.
Я її питаю:
- Ти сердита на свого чоловіка?
- Ні, я йому вдячна. Ми прожили з ним 17 років. Це були найкращі роки мого життя.
Ні жалю, ні озлоблення ...
- А чому він тебе покинув?
- Не знаю. Напевно, покохав іншу.
Вона не захворіла, не набула рак, тому що переживання такого роду ведуть до онкології - багато переживання вдаряють по тілу. Взагалі переживання - головний переносник хворіб.
Що ж робити - сходити з розуму? Ні. Життя продовжується.
- Мене залишив Маноліс (Яніс, Петрос ...)
- Коли?
- Два роки тому.
- І що ти робиш?
- Живу думками.
- А він?
- Одружився.
Він одружився, а ти живеш думками! Не можна жити думками.
Спробуйте вправу: три дні - чи хоча б три години - прожити так, щоб з вас не виходили порожні думки, ниття, скарги. Спробуйте всьому знаходити добре пояснення, мати, за словами старця Паїсія, світлі помисли про все.
До цієї вправи, про яку я сказав, додайте молитву: «Господи Ісусе Христе, спасибі, що Ти мене любиш, прощаєш і приймаєш таким, який я є». Щоб пішли порожні думки, важливо відчути, що ти - улюблене дитя Бога. Тому що якщо ти не відчуєш цього, тобі завжди буде чогось бракувати. А те, чого тобі бракує, ти будеш перетворювати в проблему. Порожні думки, які руйнують твоє життя, підуть, коли ти наситишся любов'ю Божою".
Архімандрит Андрей (Конанос)
[[https://www.facebook.com/share/p/1BLSLtQfYQ/?mibextid=rS40aB7S9Ucbxw6v][Хто вдарить тебе по щоці, підстав йому іншу або виконання заповідей дорога до вічності]].
[[https://www.facebook.com/reel/24776765928631656/?mibextid=rS40aB7S9Ucbxw6v][10 речей, про які не говорять, але які приводять до розлучення]].
[[https://www.facebook.com/share/p/17RNQnVJJi/][Навіщо вінчатися]].
** Інші.
[[https://www.facebook.com/share/p/1FbE8h7GPB/?mibextid=rS40aB7S9Ucbxw6v][РОЗСТАВАННЯ: нейробіологія розбитого серця]] 💔.
[[https://www.facebook.com/reel/802723648827458][Коли чоловік перетворюється на сусіда]].
**** [[https://www.facebook.com/reel/1304051397611102/?mibextid=rS40aB7S9Ucbxw6v][Просто побути бути разом]].
Психотерапевт Масару Ішіда багато років досліджував сімейні пари.
І виявив, що найщасливіші мали спільний ритуал у неділю.
Не подорож, не ресторан, а тиху годину без планів, без телефонів, без мети.
